const trinketItemsData = [
  {
    "id": 700,
    "type": "trinket",
    "name": "물고기 머리",
    "english_name": "Fish Head",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Eml_XKuwNEQLeq8iyuG_TnT4yOXQEKBbAH9qgG5Bo3C3p1ft_l2Z9m28JcZfo-mhG16qcuJf2ImoeGTciYFosQ.webp",
    "description": "썩은 냄새",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격당할 시 적에게 날아가는 푸른색 아군 파리가 1마리 /2마리/3마리생긴다.",
    "game_id": "29"
  },
  {
    "id": 701,
    "type": "trinket",
    "name": "분홍 눈알",
    "english_name": "Pinky Eye",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/DSl5t7RabxX_c-t16sZAefCGBIRtnmoMLlmxf0p-vqDP6ObI_gaZ6hULXa1wlhhx4vynFuEuCz15XTtpmTQguw.webp",
    "description": "독성 공격",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 확률적으로중독상태이상을 부여하는 눈물을 발사한다. 기본 확률은 10% /20%/33%이며, 확률은 행운에 비례하여 높아진다. 공식은 일반 장신구 기준 1/(10 - (행운 / 2))으로 행운이 18 이상이면 100%의 확률로 특수 눈물을 발사할 수 있다.",
    "game_id": "30"
  },
  {
    "id": 702,
    "type": "trinket",
    "name": "압핀",
    "english_name": "Push Pin",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/2KM4iRW62USK9qp6_bGC1T-2729IxR0aoV0GkzT6sloZ-ZPe0Q7Cid0zCsTVQL0_2_GxfwLXx4QclXtT34oY5w.webp",
    "description": "관통 공격",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 확률적으로 적과 장애물을관통하는 눈물을 발사한다. 기본 확률은 10% /20%/33%이며, 확률은 행운에 비례하여 높아진다. 공식은 일반 장신구 기준 1/(10 - (행운 / 2))으로 행운이 18 이상이면 100%의 확률로 특수 눈물을 발사할 수 있다.",
    "game_id": "31"
  },
  {
    "id": 703,
    "type": "trinket",
    "name": "탯줄",
    "english_name": "Umbilical Cord",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/yfvewht54_lGoTquuIokYpHlwTdlgC1f-janab7sH9tXgiQEPgcWKztzdsUWkJZ6CIIF8xBkwGgEaQZzwjgYZw.webp",
    "description": "태아 보호",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "빨간 하트 체력이 반 칸 /한 칸/한 칸 반이하거나 없는 동안 방 안에서 Little Steven 패시브 아이템으로 생성되는 패밀리어가 생성된다.빨간 하트 체력이 없는 캐릭터들은 상시 생성하고 다닐 수 있다.빨간 하트 체력을 조건 이상으로 회복해도 그 방에서는 남아있다. 빨간 하트 체력이 없는 캐릭터들은 상시 생성하고 다닐 수 있다.",
    "game_id": "33"
  },
  {
    "id": 704,
    "type": "trinket",
    "name": "아이의 심장",
    "english_name": "Child's Heart",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/d4GCsEkQ2UwCQu5Z4aGd0ii5XT_jujrqrCAgTDL0Ve7Ed_2_e9Qgn7JSGZWatqsn8o5R0zhDh0nr5g7p3L3wCg.webp",
    "description": "형제들을 소리쳐 부르고 있다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 10% /20%/50%확률로 방 보상이 빨간 하트로 대체된다. 상자를 열거나 색돌, 슬롯머신류, 거지류를 부술 때 33% /66%/100%확률로 보상에서 하트류 픽업 아이템이 추가로 하나 나온다. 더럽혀진 카인은 아이템을 분해할 때도 적용되며 이는 비슷한 효과를 가진 다른 장신구들(Rusted Key, Match Stick, Safety Cap, Ace of Spades)에게도 똑같이 적용된다.",
    "game_id": "34"
  },
  {
    "id": 705,
    "type": "trinket",
    "name": "휜 뿔",
    "english_name": "Curved Horn",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Lar-DlsjLvUNAZhCV4h3_F4VmPzIPeMArLkFOI3gKP32rG02HWe2P7uHj_6rG2rGN_ShFie_6z0KYAmKa5C2Vw.webp",
    "description": "DMG up",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격력 최종 계산 후, 이 장신구가 추가로공격력을 2 /4/6증가시킨다. 단 일부 배율에 적용되는데 대상은 다음과 같다.Magic Mushroom 또는 Cricket 's Head(중첩이 되지 않으므로) : 1.5배가 곱해져 증가한다.Soy Milk : 80%가 감소되어 증가한다.Odd Mushroom : 35%가 감소되어 증가한다. Magic Mushroom 또는 Cricket 's Head(중첩이 되지 않으므로) : 1.5배가 곱해져 증가한...",
    "game_id": "35"
  },
  {
    "id": 706,
    "type": "trinket",
    "name": "녹슨 열쇠",
    "english_name": "Rusted Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/3EE1qNRJWsrMOWDZJCCqQhNW73iA5XZOS2fWkgP_Nnldaz3o8_3-oryhV9YsKYgi7ulCCaGjz3BKLYLEwOtUWw.webp",
    "description": "운이 좋은 것 같아?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 10% /20%/50%확률로 방 보상이 열쇠로 대체된다. 상자를 열거나 색돌, 슬롯머신류, 거지류를 부술 때 33% /66%/100%확률로 보상에서 열쇠류 픽업 아이템이 추가로 하나 나온다.",
    "game_id": "36"
  },
  {
    "id": 707,
    "type": "trinket",
    "name": "염소 발굽",
    "english_name": "Goat Hoof",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/r9X79fxoyOWRJcGMeTF6uNlzYfCZZBsrReFI1r_EnxCVzUBr4rDP7KakWPdo2UtF2C5K3IYdA8hgVkDtwIRQcg.webp",
    "description": "이동 속도 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "이동 속도+ 0.15/+ 0.3/+ 0.45",
    "game_id": "37"
  },
  {
    "id": 708,
    "type": "trinket",
    "name": "엄마의 진주",
    "english_name": "Mom's Pearl",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/1aobC4I_TfPfz1SNhnmdXoK64Igg4RUxlGaIqQiLKYEl_B_wQHPul9ItWUwKcJn5dogMHuCnEGLSGjzkxfwuPA.webp",
    "description": "순수함을 발하고 있다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "일반적인 하트류 픽업 아이템이 드랍될 때 10% /20%확률로 소울 하트로 대체된다.",
    "game_id": "38"
  },
  {
    "id": 709,
    "type": "trinket",
    "name": "암",
    "english_name": "Cancer",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/1qYF9b8MUCsJlcoC6t-yDFOuIJq-vtjSdG1LPdPKdFRQlFWp52SDuIOBa9F3l9iMpcN6DNayxBQVMSTsBwQc1w.webp",
    "description": "우와 암이다!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 속도+ 1/+ 2/+ 3.이 공격 속도 증가는 한계치를 초과할 수 있다. 오리지널 시절부터 역사와 전통을 자랑하는 1티어 장신구였으나, 리펜턴스에서 공격 속도 공식이 바뀌면서 위력이 하락했다.",
    "game_id": "39"
  },
  {
    "id": 710,
    "type": "trinket",
    "name": "빨간 누더기",
    "english_name": "Red Patch",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/adNORSUd-fRY1TtKjl0SY1bzyGRGr8bTmo2zYTKoQCk0PmeCYCq1jKyZ_L1FfvYDbw9m6OzclJwRppKeNliO6w.webp",
    "description": "분노 충전 중",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "현재 방에서 피격시 일정 확률로공격력이 1.8 증가한다. 발동 확률은 행운에 비례하여 행운이 0일 때 20% /33%/50%확률로 발동, 기본 장신구 기준 행운이 8 이상이면 100%의 확률로 공격력이 증가한다.",
    "game_id": "40"
  },
  {
    "id": 711,
    "type": "trinket",
    "name": "성냥개비",
    "english_name": "Match Stick",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/R0MWNKECIT9pLmfdPBik170N_XxAyuy65TfCRZjoB4Rq7UkqUBghzXEgqGfsBZJo5I5PSnc1eE_5iqoPtfuZNA.webp",
    "description": "타는 듯한 맛",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 10% /20%/50%확률로 방 보상이 폭탄으로 대체된다. 상자를 열거나 색돌, 슬롯머신류, 거지류를 부술 때 33% /66%/100%확률로 보상에서 폭탄류 픽업 아이템이 추가로 하나 나온다.",
    "game_id": "41"
  },
  {
    "id": 712,
    "type": "trinket",
    "name": "행운의 발가락",
    "english_name": "Lucky Toe",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/M8Ffa6gXEAKyrU0G2Pfb0iXhMyKn6w0Cw6A4YX7B3cYK2fdqntIDJ3Z6Pp9pcnUIwGqOXT2PJhdebtQPz_447w.webp",
    "description": "행운 증가!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "행운+ 1/+ 2/+ 3 상자를 열거나 색돌, 슬롯머신류, 거지류를 부술 때 33% 확률로 보상에서 픽업 아이템이 추가로 하나 나온다.",
    "game_id": "42"
  },
  {
    "id": 713,
    "type": "trinket",
    "name": "저주받은 해골",
    "english_name": "Cursed Skull",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/BTnL3BfvndMVG58DAhcBWO_ACcnoyDBr6u0glA8z_SCPZNOQ5OI5KabQDIkeIESdkoOqHVvPXBfzKRNyveXOpQ.webp",
    "description": "저주라고?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소울, 블랙하트와 상관없이 현재 빨간 하트 체력이 반 칸 /한 칸이하인 상황에서 피격 시 랜덤한 방 /특수방으로 순간이동한다. 빨간 하트 체력이 없는 캐릭터는 효과를 발동할 수 없으며 포가튼의 뼈하트 체력 및 획득한 뼈하트 역시 계산에서 제외된다.",
    "game_id": "43"
  },
  {
    "id": 714,
    "type": "trinket",
    "name": "스페이드 10",
    "english_name": "Ace of Spades",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/TY8oKTXBiKk0iavctl45ma7rofNJdgU6EQSoqq4RAcG39_z7brzjpVX8YlX1NMG6QrqERppfWVjoxU4JXruSKw.webp",
    "description": "카드 뽑기의 행운",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 10% /20%/50%확률로 방 보상이 카드로 대체된다. 상자를 열거나 색돌, 슬롯머신류, 거지류를 부술 때 33% /66%/100%확률로 보상에서 카드가 추가로 하나 나온다.색돌과 나무 상자를 제외하면 동전, 폭탄, 열쇠, 하트 무더기를 드랍할 때에만 카드가 추가로 하나 나온다.",
    "game_id": "45"
  },
  {
    "id": 715,
    "type": "trinket",
    "name": "아이작의 포크",
    "english_name": "Isaac's Fork",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Kf6Gv_xzQJW-voduKo1Wv5J9Uy8VDaherjtzNPJUYCvapEr9tsb-yg_1NZ5TlPXghEvdBeNHimzANKg4neEWrg.webp",
    "description": "적들은 맛있어",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방을 클리어 시 일정 확률로 하트가 반 칸 /한 칸/한 칸 반회복되며 키퍼는 코인체력을 한칸 채워준다. 발동 확률은 행운에 비례하여 발동 확률은 행운에 비례하여 공식은 1/(10 - (행운 / 2)). 최종적으로 행운이 18 이상이면 100%의 확률로 방 클리어 시 체력이 회복된다.",
    "game_id": "46"
  },
  {
    "id": 716,
    "type": "trinket",
    "name": "찢어진 페이지",
    "english_name": "A Missing Page",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/nd4GmINtFdyT2LLLTAiqkZRGyq1yQUlmFS2znPrXclUn9btRgtNWhmTWqwzm73R8D_3M5T87W217EOb1U-XT5g.webp",
    "description": "힘을 지니고 있다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 전체의 적에게 40의 대미지를 입히는 아이템들의 대미지가 40 /80/120증가한다.해당하는 아이템 목록블랙 하트Blood RightsDry BabyThe NecronomiconThe NegativeXIII - Death 카드 해당하는 아이템 목록블랙 하트Blood RightsDry BabyThe NecronomiconThe NegativeXIII - Death 카드",
    "game_id": "48"
  },
  {
    "id": 717,
    "type": "trinket",
    "name": "피묻은 동전",
    "english_name": "Bloody Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/QXcSeakVfeGhCZNwDK1P4OGQKyNtNh0UFyTicKEpeDNCcBeNZHsIXt_G3_Of5r8S23CSpmG1w1ay1Zv0PQ3wrA.webp",
    "description": "피 부자",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 빨간 하트 픽업 반 칸을 드랍한다. 일반 페니를 기준으로 확률은 25% /50%/75%이며, 동전의 가치에 따라 확률이 다르다. 아래의 확률은 일반 장신구 기준.페니(1코인): 25%1+1 페니(2코인): 43.75%니켈(5코인): 76.27%다임(10코인): 94.37% 페니(1코인): 25%",
    "game_id": "49"
  },
  {
    "id": 718,
    "type": "trinket",
    "name": "타버린 동전",
    "english_name": "Burnt Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/gO4JlRyqb_1FjCHRWTBmpnTkneslR3JGLsehVCqnvHUxedOMdfKwS0H_f16ln9C26OiRW_qF9qz3AoQX-fr9jw.webp",
    "description": "폭탄 부자",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 폭탄을 드랍한다. 일반 페니를 기준으로 확률은 25% /50%/75%이며, 동전의 가치에 따라 확률이 다르다. 아래의 확률은 일반 장신구 기준.페니(1코인): 25%1+1 페니(2코인): 43.75%니켈(5코인): 76.27%다임(10코인): 94.37%오직 일반 폭탄만 드랍되며 특정 시너지 아이템이 있을 경우에만 1+1 폭탄을 드랍할 수 있다. 트롤 폭탄도 나올 수 있다. 페니(1코인): 25%",
    "game_id": "50"
  },
  {
    "id": 719,
    "type": "trinket",
    "name": "납작한 동전",
    "english_name": "Flat Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/uB_itnfss1nt8HI4JbCVrtCvxC5XRQlsyoDsesH6zb6KUCvzezr4tklL3rfr_qcoF9rhYZJSWCuiyp0LWO424Q.webp",
    "description": "열쇠 부자",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 열쇠를 드랍한다. 일반 페니를 기준으로 확률은 25% /50%/75%이며, 동전의 가치에 따라 확률이 다르다. 아래의 확률은 일반 장신구 기준.페니(1코인): 25%1+1 페니(2코인): 43.75%니켈(5코인): 76.27%다임(10코인): 94.37%오직 일반 열쇠만 드랍되며 Humbling Bundle이 있는 경우에만 50% 확률로 1+1 열쇠가 드랍된다. 페니(1코인): 25%",
    "game_id": "51"
  },
  {
    "id": 720,
    "type": "trinket",
    "name": "가짜 동전",
    "english_name": "Counterfeit Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/5SPEx8UYCsFoa0Et7zV6QxElhlA02H2QZG1vNRvBWZVnHRExpgtTGZ1ZdPkgyPZNnLGrvhiG4DPDKJtBXm_h8w.webp",
    "description": "동전 부자",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 1원 /2원/3원을 더 얻는다. 동전의 가치에 따라 확률이 다르며 그 확률은 다음과 같다.페니(1코인): 50%1+1 페니(2코인): 75%니켈(5코인): 96.88%다임(10코인): 99.9% 페니(1코인): 50%",
    "game_id": "52"
  },
  {
    "id": 721,
    "type": "trinket",
    "name": "진드기",
    "english_name": "Tick",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/x0vTXXtjSghNnfGabrCmPxs0Q3BTvkm6wbHoAOnE4GTmoy8iidIJWqV5zZkrgYO4L687IkmWl_--Spl1CCYMgA.webp",
    "description": "안 떨어져..",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "보스를 포함한 적의 체력이 60 이상인 경우 체력이 15% /30%깎여서 등장한다.아군 영구 매혹 몬스터의 체력도 깎인다.The Beast전의 4기사들은 효과를 받지 않는다. 아군 영구 매혹 몬스터의 체력도 깎인다.",
    "game_id": "53"
  },
  {
    "id": 722,
    "type": "trinket",
    "name": "아이작의 머리",
    "english_name": "Isaac's Head",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/TLpXYZW0JA8KlOngVyandcvqwJufcJFc4xrQE20L7mStiItspzQH9qZw7rqQvspq6Z-XFBJeQvvY4XguRo24Kg.webp",
    "description": "죽은 친구",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터를 따라다니면서 캐릭터가 공격할 때 적을관통하는공격력 3.5 /스탯 공격력만큼의 대미지/스탯 공격력의 1.5배에 해당하는 대미지의 눈물을 발사하는 머리 패밀리어가 생긴다.",
    "game_id": "54"
  },
  {
    "id": 723,
    "type": "trinket",
    "name": "매기[10]의 믿음",
    "english_name": "Maggy's Faith",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/4tyYKVVDigz9tY50FWe1vt42j4WM9QOcFVHUE9ya1afN24wjd1HuNOqwXDmJ90goYFmMeBPsIO7NIuothEHoWA.webp",
    "description": "믿음의 보상",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "매 층을 시작할 때마다 이터널 하트 1개 /2개/3개를 획득한다.황금 Maggy's Faith이거나, Mom's Box 소지시에는 사실상 매 스테이지 시작 때마다 최대 체력 1칸을 얻는 장신구가 된다.더 포가튼의 경우 층을 시작한 시점에서 조작하고 있던 캐릭터에게 이터널 하트가 제공된다.키퍼로는 하트는 커녕 파리조차도 생성되지 않는다. 황금 Maggy's Faith이거나, Mom's Box 소지시에는 사실상 매 스테이지 시작 때마다 최대 체력 ...",
    "game_id": "55"
  },
  {
    "id": 724,
    "type": "trinket",
    "name": "유다의 혀",
    "english_name": "Judas' Tongue",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/T482xZijVHsytur2SEZ7Th8rE6I-S1gml-ChYdHV_CNKX85TVGbhqjLfWMHUAKfnBXxW0IiDrVo_i0FI3jLLXQ.webp",
    "description": "대가는 이미 받았다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "최대 체력 2칸을 요구하는 체력 거래의 요구량이 최대 체력 1칸을 요구하도록 감소된다.체력 거래가 동전 거래로 바뀌었을 경우에는 적용되지 않는다. 체력 거래가 동전 거래로 바뀌었을 경우에는 적용되지 않는다.",
    "game_id": "56"
  },
  {
    "id": 725,
    "type": "trinket",
    "name": "???의 영혼",
    "english_name": "???'s Soul",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/zKW1RDUEB9oZhT5o7Az9lCJ8WzAuPRv1aXUW8lPrhd1xYk1fb-Mb2W9ZD5lwj9WOnpzVKpXnqin92H8bMgMOxw.webp",
    "description": "상상 속의 친구",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "벽을 대각선으로 튕겨다니면서 캐릭터가 공격할 때 그 방향으로유도능력을 가진공격력 3.5의 눈물을 발사하는 패밀리어가 1명 /2명/3명생긴다.",
    "game_id": "57"
  },
  {
    "id": 726,
    "type": "trinket",
    "name": "삼손의 머리채",
    "english_name": "Samson's Lock",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/2j70V2RjPafVcqJwmeoB6FHONjF7dJuI248Ce6tEFRiOe5YChieZx_Fk1wM3l7nFufmwSESPrh6OiZwohrU9ww.webp",
    "description": "분노가 차오르다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "그 방 한정으로 적을 처치할 때마다 일정 확률로 공격력이 0.5씩 상승해 최대 5까지 올라간다. 발동 확률은 행운에 비례하여 행운이 0일 때 6.66% /13.33%/25%확률로 발동, 행운이 10 이상이면 100%의 확률로 적을 처치 시 공격력이 증가한다.",
    "game_id": "58"
  },
  {
    "id": 727,
    "type": "trinket",
    "name": "카인의 눈",
    "english_name": "Cain's Eye",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/aONRVhzyOqA1YyZKGUhIJIBKqsdeV7cMWMS5lXfUGuNpYEF1_5nQ5Czxh3Tvv3ib3v1Ii5A7Ux2wFbSUaAYLcA.webp",
    "description": "네 운명이 보이리라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "층을 시작할 때 일정 확률로 The Compass 효과가 발동되어 맵 상에서 특수 방의 위치가 공개된다. 기본 확률은 25% /50%/75%이며, 확률은 행운에 비례하여 높아진다. 공식은 일반 장신구 기준 1/(4 - 행운)으로 행운이 4 이상이면 사실상 다음 층부터 The Compass를 소지하는 것이나 다름이 없어진다.",
    "game_id": "59"
  },
  {
    "id": 728,
    "type": "trinket",
    "name": "이브의 새 다리",
    "english_name": "Eve's Bird Foot",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/zOQTJyUwEoNPpsIckREe2XFhCg5DeH77js1-eKYLZCSwD44OtoXy9fv5AXJE33gJ8brk83uwG9TFYtftS9FZww.webp",
    "description": "저 세상에서 온 복수",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "해당 방 안에서 적을 죽이면 5% 확률로 Dead Bird의 새와 유사한 새가 생성되어 적을 향해 날아가 접촉 대미지를 준다.이 새는 다리가 하나 없는 투명한 생김새를 띄며, 일반적인 Dead Bird로 생성되는 새보다 공격력이 약한 초당 4의 대미지를 입힌다.한 방에서 새는 한 마리만 생성할 수 있다. 이 새는 다리가 하나 없는 투명한 생김새를 띄며, 일반적인 Dead Bird로 생성되는 새보다 공격력이 약한 초당 4의 대미지를 입힌다.",
    "game_id": "60"
  },
  {
    "id": 729,
    "type": "trinket",
    "name": "왼손목",
    "english_name": "The Left Hand",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/5dC4YaycdiIM35qQULMaF5xh-ysPOLxgBQLlB29SpcLEtGuh-md_2cxoBcJYrhmw9yNiTTNtAaJrQz1TBIw18Q.webp",
    "description": "어둠의 보상을 거두어들이다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Old Chest와 Mega Chest를 제외한, 앞으로 등장하는 모든 상자가 빨간 상자로 등장한다.Chest의 시작 방에 등장하는 황금 상자 4개도 빨간 상자로 대체되며, 이 경우 Dark Room의 시작 방에 존재하는 빨간 상자처럼 악마 방 배열의 아이템을 체력 거래로 제시한다. Chest의 시작 방에 등장하는 황금 상자 4개도 빨간 상자로 대체되며, 이 경우 Dark Room의 시작 방에 존재하는 빨간 상자처럼 악마 방 배열의 아이템을 체...",
    "game_id": "61"
  },
  {
    "id": 730,
    "type": "trinket",
    "name": "삼킨 동전",
    "english_name": "Swallowed Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/cV_BrIq-b2os1bHnR-f0jhpnJQzlCMSWn8PkLcBccpcQ-fvR6JE8T8cYb5uJyEiZzBB_lO6hz43AKvVyB-PIvA.png",
    "description": "꿀꺽!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격을 당하면 무작위 동전을 1개 /2개/3개드랍한다.(더럽혀진) 키퍼는 돈을 50%의 확률로 드랍한다. (더럽혀진) 키퍼는 돈을 50%의 확률로 드랍한다.",
    "game_id": "1"
  },
  {
    "id": 731,
    "type": "trinket",
    "name": "굳은 응아",
    "english_name": "Petrified Poop",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/c9arBoqzDl2AQX2w9dK114U3uEZ6SrzX29TbZNjWDY1i-B30IQAeB3Z9tAvh338qpkuEN4nF5WrdoWo91tCXwg.png",
    "description": "운이 좋은 건가?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "똥을 부술 시 기타 아이템이 나올 확률이 50% /60%/70%로 증가한다. 일반적인 드랍 이외에도 똥을 부술 때 적은 확률로 얻을 수 있다.",
    "game_id": "2"
  },
  {
    "id": 732,
    "type": "trinket",
    "name": "AAA 건전지",
    "english_name": "AAA Battery",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/R4vHBQ4aI2fIN9oFD_YkYeHE3nu1_iuGQdPYqjX9_eap28lipwtXX_GIJOVMwjUBsjyDbQrPVE0B7BspfOrsxQ.png",
    "description": "세류충전",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방을 클리어해 게이지가 충전된 이후 액티브 아이템의 완충에 필요한 충전 게이지가 1칸 /2칸/3칸남았다면 남은 게이지를 자동으로 채워준다.게이지가 충전되는 칸 수 이하이거나, 자동으로 충전되는 아이템에는 적용되지 않는다. 게이지가 충전되는 칸 수 이하이거나, 자동으로 충전되는 아이템에는 적용되지 않는다.",
    "game_id": "3"
  },
  {
    "id": 733,
    "type": "trinket",
    "name": "고장난 조종기",
    "english_name": "Broken Remote",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ZsY4lnBjcQgJ8nKlx460kVl4DA7Jcp-2tA-G8UxMqnvdlf745zfyEX0Oua7Hg8SVN9qeVoyMd_paWOvbjdfqnw.png",
    "description": "고장났다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "액티브 아이템을 사용할 시 스테이지의 무작위 방 /클리어하지 않은 방으로 이동한다.스테이지에 존재하지 않는 악마방/천사방과 같은 방으로는 이동할 수 없다. 스테이지에 존재하지 않는 악마방/천사방과 같은 방으로는 이동할 수 없다.",
    "game_id": "4"
  },
  {
    "id": 734,
    "type": "trinket",
    "name": "깨진 자석",
    "english_name": "Broken Magnet",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/lbxWRq6EhbEi3mo0Pf4TTCf1ZA0barvHo-xE9-6aCS1J0iUcXTWZw5GXCv4E56nfwPKepd050HBWr5Odvj30ZA.png",
    "description": "반은 멀쩡해",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터가 있는 방향으로 동전 /픽업 아이템이 열쇠벽돌을 제외한 모든 오브젝트와 지형을 무시하고 천천히 끌려온다.",
    "game_id": "6"
  },
  {
    "id": 735,
    "type": "trinket",
    "name": "묵주 구슬",
    "english_name": "Rosary Bead",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/pvQjilFiyIOeuN3cN3dr7XA4s8GnK5jF0oYpLpB0EIjTe7C2tdZ0zQTpdQdoU1mb6L2h7lUYbVi2tjJPUbzSAg.png",
    "description": "신앙심 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 시 악마방 대신 천사방이 등장한다. 장착하고 있는 동안 책방에서 45% 확률로, 상점에서 13% 확률로 The Bible 액티브 아이템이 나오게 된다.",
    "game_id": "7"
  },
  {
    "id": 736,
    "type": "trinket",
    "name": "카트리지",
    "english_name": "Cartridge",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/RIv2pt7mwjEI9vD_vsfIgOg-y0YU6p6o5mXj505mNmuOcR266toAd28C5DLUi0glgo9e7nruAXaOA9qWHzn6Tw.png",
    "description": "추억의 물건",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 일정한 확률로 The Gamekid 효과가 발동된다. 발동 확률은 행운에 비례하여 행운이 0일 때 5% /10%/15%확률로 발동, 행운이 38 이상이면 피격 시 100% 확률로 발동한다.",
    "game_id": "8"
  },
  {
    "id": 737,
    "type": "trinket",
    "name": "외상 증서",
    "english_name": "Store Credit",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/YScI_0MepNFR_kQ4jMSXDq9FL4tPAGqkWk6D_ymsXwRhf1L8OtWOLWa8FCYlSbkbE2R3KWTAATH6bKXnVIeejg.png",
    "description": "좋습니다!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지하는 동안 상점의 모든 아이템의 거래 가격이 무료가 된다. 아이템을 무료로 구매하면 장신구는 사라진다.상점이 아닌 곳의 동전 거래는 무료가 되지 않는다. 상점이 아닌 곳의 동전 거래는 무료가 되지 않는다.",
    "game_id": "13"
  },
  {
    "id": 738,
    "type": "trinket",
    "name": "굳은살",
    "english_name": "Callus",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/xxMAv6BPBKmLY-1iT7_8KS3fYdP8dypUW87IMX_cA8pKZVIlUSSl3tNGVQxNnJmanqX8u1qMhMnGB8Q_YCDivg.png",
    "description": "강해진 듯한 기분",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "바닥의 가시 및 적이 깐 장판에 면역이 된다.Mama Gurdy, The Pile 보스가 생성한 가시, 저주방 문, 가시 상자 및 가시돌, 그리드 모드의 정지 버튼, 희생방의 가시는 막아주지 못한다. Mama Gurdy, The Pile 보스가 생성한 가시, 저주방 문, 가시 상자 및 가시돌, 그리드 모드의 정지 버튼, 희생방의 가시는 막아주지 못한다.",
    "game_id": "14"
  },
  {
    "id": 739,
    "type": "trinket",
    "name": "행운의 돌조각",
    "english_name": "Lucky Rock",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/V13AEE1O6c54HL0tBPL_bsvZQxwzj-aqkKoT3fxcwvC7mTPq5TRE4nn5wbl6XvW6sxYpz5k9ggSL6nywCf8puQ.png",
    "description": "속에 뭔가가 있다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "돌류 장애물을 파괴했을 때 33% 확률로 페니 1개 /2개/3개가 드랍된다. 2023년 3월 10일 현재 언락율이 76.1%로 언락 대상 장신구 중에 가장 높다.",
    "game_id": "15"
  },
  {
    "id": 740,
    "type": "trinket",
    "name": "엄마의 발톱",
    "english_name": "Mom's Toenail",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/8fqsbPy3K4RWlFGKGxTiAZZCkWQT5x0ZshVVqVLaYjAi-eDMAfp4zQE7jJJlC4wDYESPCTcB0rvVQP8E_lwa3g.png",
    "description": "???",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "전투 중이거나, 이 장신구를 내려놓을 때 일정 확률로 300의 대미지를 주는 엄마 발이 1번 /2번/3번떨어질 수 있다.당연하지만 이 발에 맞으면 하트 1칸의 대미지를 입으니 주의. 당연하지만 이 발에 맞으면 하트 1칸의 대미지를 입으니 주의.",
    "game_id": "16"
  },
  {
    "id": 741,
    "type": "trinket",
    "name": "검은 립스틱",
    "english_name": "Black Lipstick",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Du_wM0AC1CFeU33GQIepOqVMYqdq37MWEOjjOV2r5BE0OlMHRJCU6ukhzlcW2tO6aTeik3muKfDJPq-oZaagng.png",
    "description": "악함 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "하트 픽업이 블랙 하트로 대체될 확률이 10% /20%/33%증가한다. 사실상 체감 효과는 다른 하트 드랍 관련 아이템들에 비해 매우 미미한 수준.",
    "game_id": "17"
  },
  {
    "id": 742,
    "type": "trinket",
    "name": "주보",
    "english_name": "Bible Tract",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/yuzK83tgn9R2EV-4sWgq2ey4P0lD9pi6_Q7WIk3t0DjdKhQ7hqCogVhhCmoBW50EX-hpeLbyTTiqqCZjIpWydg.png",
    "description": "신앙심 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "하트 픽업이 이터널 하트로 대체될 확률이 3% /6%/9%증가한다.",
    "game_id": "18"
  },
  {
    "id": 743,
    "type": "trinket",
    "name": "종이 클립",
    "english_name": "Paper Clip",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/2Pa3-zSmVGbudBm1XUEPK16Yodh2BVR9SWe0sb4ubpUfF_rPfyK_jP4mCYNTRMiCWV2kD70hx01MzR3LZVjpAQ.png",
    "description": "잠금 해제의 달인",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Mega Chest를 제외한, 여는데 열쇠가 필요한 상자 /열쇠 블록/잠긴 문을 열쇠 없이 열 수 있다. 일반적인 드랍 이외에도 열쇠 거지가 충분한 양의 열쇠를 얻고 떠날 때 간혹 드랍한다.",
    "game_id": "19"
  },
  {
    "id": 744,
    "type": "trinket",
    "name": "원숭이 손",
    "english_name": "Monkey Paw",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/-jEnZHfdcrYPG5AsJQM6hdzfBfhl97cYIHGXuin007FQJFUqjw7zifTwRxuIqpHgPJLsxP2RzB_A3bHE7LPH7A.png",
    "description": "소원이 이루어지다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격을 입었을때 빨간 체력만 반 칸 남게 되면 블랙 하트를 1개 /2개/3개드랍한다.같은 방에서 연속으로 발동할 수 있다. 같은 방에서 연속으로 발동할 수 있다.",
    "game_id": "20"
  },
  {
    "id": 745,
    "type": "trinket",
    "name": "신비한 종이",
    "english_name": "Mysterious Paper",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/TjizPoD4kRbaxe5q-zgsWS2PvxiymI-aAf04k2ETPdnq41eO4axBgaQGx_jdUdvh9Uud3GFyzLIv7OJZWGbstw.png",
    "description": "???",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지하는 동안 매 프레임마다 하단의 아이템들 중 하나 /둘의 효과를 무작위로 얻는다. 피격 시 발동되는 효과가 대부분이기 때문에 사실상 '피격당할 때마다 하단의 아이템 효과 중 하나가 발동된다.'라고 봐도 무방하다.The Polaroid : 빨간 하트 체력이 없거나 남은 빨간 하트 체력이 반 칸일 때 피격 시 5초간 보호막이 발동된다.The Negative : 빨간 하트 체력이 없거나 남은 빨간 하트 체력이 반 칸일 때 피격 시 방 안의 모든 ...",
    "game_id": "21"
  },
  {
    "id": 746,
    "type": "trinket",
    "name": "악마 꼬리",
    "english_name": "Daemon's Tail",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/vAn1S43y2DJ3395vVhQVQldt1Pa1F-STU1DfzYLnuIIV_ltzb-nxZgXHIRQ2Qje8GBcCiSthVzB6JETdAf37zA.png",
    "description": "악함 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 드랍되는 하트류 픽업이 80% 확률로 열쇠로 대체된다. 고정 하트 드랍을 제외한 모든 하트 드랍이 블랙 하트로 대체된다.",
    "game_id": "22"
  },
  {
    "id": 747,
    "type": "trinket",
    "name": "실종 포스터",
    "english_name": "Missing Poster",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/bW1QkQd8xzWJypCoiGAP_cv-KNlGPXShT9AleKvWg-33a-PFp9LEfTxwW1Ip7bpr3ja1rf-UDSMivgmTua2zTA.png",
    "description": "???",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "이 장신구를 가진 채 희생방에서 자살하면 장신구가 소멸하고 더 로스트 캐릭터로 부활함과 동시에 해당 캐릭터가 언락된다.리버스 당시에는 더 로스트로 부활 대신 더 로스트 언락 방법에 대한 단서를 주는 퍼즐 조각이 유서에 나왔으나, 유저들의 데이터마이닝으로109시간만에 연락 방법이 밝혀진 이후 애프터버스에서 현재의 효과로 리워크되었다. 리버스 당시에는 더 로스트로 부활 대신 더 로스트 언락 방법에 대한 단서를 주는 퍼즐 조각이 유서에 나왔으나, 유...",
    "game_id": "23"
  },
  {
    "id": 748,
    "type": "trinket",
    "name": "똥전",
    "english_name": "Butt Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/RxY0-EmB5FphaRTowkhaAHLPoKm73YvgiRVaKBBvxt4BBh8ITuTIhvv3uTRKrtkAiHfUkLml1SH6GKj2Nrr2VQ.png",
    "description": "가스 부자",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전을 얻으면 적과 픽업 아이템을 밀어내며 맞은 적에게중독상태이상을 입히는 방귀를 뀐다. 똥에서 동전이 나올 확률이 추가로 20% /30%증가한다.",
    "game_id": "24"
  },
  {
    "id": 749,
    "type": "trinket",
    "name": "이상한 초콜릿",
    "english_name": "Mysterious Candy",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/fXZIFbmc9651GFNmuYukrxLnRGHazrQ7my8GLoU7pzPwVE9rDZM1aMUMw0SnuS0U8RKmHvam_eCzgHDsOTRJeA.png",
    "description": "으엑!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "상단의 타이머를 기준으로 매 30초마다 캐릭터가 있는 자리에다 똥을 생성하거나 방귀를 뀔 수 있다.방귀는 적에게 6의 대미지를 입히고 적과 탄환을 밀쳐낸다.황금 Mysterious Candy 소지 시, 똥 대신황금 똥을 싼다. 일반 장신구 + Mom's Box로는 효과를 볼 수 없다. 방귀는 적에게 6의 대미지를 입히고 적과 탄환을 밀쳐낸다.",
    "game_id": "25"
  },
  {
    "id": 750,
    "type": "trinket",
    "name": "부서진 앙크",
    "english_name": "Broken Ankh",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/lFMxMmDF07ffBEvH7R-aHW2kobOOXDqzPgFFiR6FR41Zir_L-kwKrH432V5zm1_LPeHhYZqiO1YfSfdecMqP1w.png",
    "description": "영원한 생명?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "해당 장신구를 소지한 채로 사망 시 22% /33%/50%확률로 ??? 캐릭터로 부활한다.행운 수치의 영향을 받지 않는다.더럽혀진 ??? 캐릭터는 더럽혀진 ??? 그대로 부활한다. 행운 수치의 영향을 받지 않는다.",
    "game_id": "28"
  },
  {
    "id": 751,
    "type": "trinket",
    "name": "빛나는 돌",
    "english_name": "Shiny Rock",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/cClyXf4u8RA0hwUZ9CHVlZumnfwaD8LnrbBhbTtIm-qBL2OjIUh3kXEliH9H_yJTBO5U2hCn5uU7kXE7jsd-1g.webp",
    "description": "형제들을 위하여 빛낼지어다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "x가 표시된 바위, 레트로 보물방 입구를 가리는 돌,비밀방으로 연결되는 벽이 현재 방에 있을때 10초 /5초마다 흰색으로 반짝인다.",
    "game_id": "62"
  },
  {
    "id": 752,
    "type": "trinket",
    "name": "안전 가위",
    "english_name": "Safety Scissors",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ev3ty6UzaO3AHpGDMZV72zz_8IvPM-IWkrCRsu_Lm8jRNTUvBacTYUpzYogEU79N6AlPFP07S99BvKHJPW87NQ.webp",
    "description": "도화선 자르기",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "트롤 폭탄들이 터지기 직전에 폭탄 픽업 아이템으로 변한다. 무슨 트롤 폭탄이었냐에 따라 바뀌는 폭탄 픽업이 다르다.일반 트롤 폭탄: 일반 폭탄 픽업슈퍼 트롤 폭탄: 1+1 폭탄 픽업황금 트롤 폭탄: 황금 폭탄 픽업 일반 트롤 폭탄: 일반 폭탄 픽업",
    "game_id": "63"
  },
  {
    "id": 753,
    "type": "trinket",
    "name": "무지개 벌레",
    "english_name": "Rainbow Worm",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/kruu491UwPWOiECHA7QEGUqpBp5ddgiRMWz29aWNsKC-FrIEHtJVnd3-WBz4o0VDT4cXuQueN062SRZKkW-pMg.webp",
    "description": "둥글슈욱지그재그",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "장신구를 획득한 순간부터 3초마다 눈물 공격시 Worm 장신구들의 효과를3배 강화해서/4배 강화해서얻는다. 바뀌는 순서는 하단의 목록을 참조.Worm 장신구 변환 순서Pulse WormRing WormTape WormWhip WormWiggle WormFlat WormHook WormLazy WormOuroboros WormBrain Worm Worm 장신구 변환 순서Pulse WormRing WormTape WormWhip WormWiggle...",
    "game_id": "64"
  },
  {
    "id": 754,
    "type": "trinket",
    "name": "게으른 벌레",
    "english_name": "Lazy Worm",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ooEoD_8-raxtt_-XIqyot76rHyyiycXEsIg1zNW_RWrtPy4mfoW8rjzcXW3PaMLCV0JgUtyB2HE2Nh7XkEFHvA.webp",
    "description": "하암",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격력 최종 계산 후, 이 장신구가 추가로공격력을 0.5 /1/1.5증가시킨다. 눈물 속도- 0.5/- 1/- 1.5",
    "game_id": "66"
  },
  {
    "id": 755,
    "type": "trinket",
    "name": "갈라진 주사위",
    "english_name": "Cracked Dice",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/-cAOFL_kqHadTBt4K5lAZ2PsEOh6bl0neDlwQMieNtiGPz_Fa97U0UXPCDc2aFYYBlfGN_tX3JCsJ4GoEr8EJg.webp",
    "description": "저주에 걸린 것...같다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 50% /75%/100%확률로 하단의 주사위 효과 중 하나가 발동될 수 있다.The D6: 방 안에 있는 액티브/패시브 아이템을 리롤한다.D8: 캐릭터의 이동 속도, 공격력, 공격 속도, 사거리를 무작위로 리롤한다.D10: 방 안의 몬스터들을 한 단계 낮은 몬스터들로 바꾼다.D12: 방 안의 장애물들을 다른 장애물로 리롤한다.D20: 방 안의 픽업 아이템, 장신구, 상자를 다른 픽업 아이템, 장신구, 상자로 리롤한다. The D6: 방...",
    "game_id": "67"
  },
  {
    "id": 756,
    "type": "trinket",
    "name": "슈퍼 자석",
    "english_name": "Super Magnet",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/C-_nnWNEwsaPtJmNr85E9A8Mz1d9iKx0ZNgIBV31CSoj9giND_S8UVyqJiSL6b8qgm4aUQx2su_UgoH56FRWsQ.webp",
    "description": "끌어당기기",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터가 있는 방향으로 픽업 아이템, 적들,장신구, 자루,상자가 열쇠벽돌을 제외한 모든 오브젝트와 지형을 무시하고 천천히 끌려온다.하트류는 회복이나 추가될 체력이 없다면 끌려 오지 않는다. 하트류는 회복이나 추가될 체력이 없다면 끌려 오지 않는다.",
    "game_id": "68"
  },
  {
    "id": 757,
    "type": "trinket",
    "name": "흐려진 폴라로이드",
    "english_name": "Faded Polaroid",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/jVwF0mkpApQghu0PCUsKL4WJJxHEKliwgY411nSNxmiNDGMdRrqM3oTuaq7PLMpRyvfPDng_STH8hRu-DNbSGQ.webp",
    "description": "흐려진 기분",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "때때로 아이작이 보호색을 띄면서, 방 안의 모든 적에게 보호색을 띄는 동안혼란상태이상 효과를 부여한다.황금 Faded Polaroid거나, Mom's Box 소지 시보호색 지속 시간이 증가한다.혼란은 투명해 질 때에만 적용 되므로, 그 후에 소환된 몹에겐 혼란이 적용 되지 않는다. 황금 Faded Polaroid거나, Mom's Box 소지 시보호색 지속 시간이 증가한다.",
    "game_id": "69"
  },
  {
    "id": 758,
    "type": "trinket",
    "name": "이",
    "english_name": "Louse",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/PbYM9aR6NKslF500oHWRZ-DNpyMgZVSUs0emk3vX1TSueKAdgmLOdxago38k7upn3LHh1YvPlmHUFel7kxmGHg.webp",
    "description": "가려워, 가려워...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "클리어하지 않은 방에 있을 때 30초마다 아군 거미가 1마리 /2마리/3마리생성된다. 방을 클리어하면 아군 거미가 생성된다.",
    "game_id": "70"
  },
  {
    "id": 759,
    "type": "trinket",
    "name": "밥의 방광",
    "english_name": "Bob's Bladder",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/akYpuG9v5ZG0qIOM1jKzV9PbefkgoDgUeZ1k6HCa1QkQl6I-w8SAR3_RC9JS5hVXqKXnkhL9ACwISQiHhfMd2Q.webp",
    "description": "오싹한 폭탄",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 시 Bob 변신 세트 아이템으로 취급한다. 폭탄을 놓으면 폭탄 아래에 녹색 장판이 생긴다. 폭발하면 장판이 잠시 후 사라진다.황금 Bob's Bladder나, Mom's Box 소지 시 이 장판이1.5배/2배커지며1.5배/2배오래 간다.",
    "game_id": "71"
  },
  {
    "id": 760,
    "type": "trinket",
    "name": "손목시계용 전지",
    "english_name": "Watch Battery",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/a0Qn2gwMatCcU-G5LRWfigZuFUEKsRK3LaHD191nmSD-zi74pAKVrIXzgcgkmcUod0NlYGyBN3S22eGOKfZilw.webp",
    "description": "약한 충전",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 배터리 픽업 아이템이 등장할 확률이 6.67% 증가한다. 방 클리어 시 액티브 아이템의 충전 게이지를 추가로 1칸 /2칸/3칸더 채울 확률이 5% 생긴다.",
    "game_id": "72"
  },
  {
    "id": 761,
    "type": "trinket",
    "name": "폭파용 뇌관",
    "english_name": "Blasting Cap",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/GYYYgBPbMnYZTBAtVKr_nlyG-M2eBatiSzQlz5XAcSIzGfADRuecrEtZwSYUzOMXdBgmo23WzoEnwi9jYrwDtg.webp",
    "description": "펑! 펑!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "폭탄이 터질때 10% /20%/30%확률로 폭탄 픽업이 드랍된다. 황금 폭탄을 이용하여 무한 파밍이 가능하나 Dr. Fetus로 발사되는 폭탄은 발동되지 않는다.",
    "game_id": "73"
  },
  {
    "id": 762,
    "type": "trinket",
    "name": "벽체 탐지기",
    "english_name": "Stud Finder",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/oeO1-RVYckPa0yJ_fAkeCie1F1knymop2i4dhAk0Zq_llCR1rPPZ0PcAFDkWv2whQrCoL00DCAtEc3wc4oNhEw.webp",
    "description": "아래에 빈 공간이 있는 것 같아...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "돌을 부술 때 0.5% /1%확률로 레트로 보물방(혹은 블랙 마켓)으로 입장하는 사다리가 생성된다.스테이지 시작 시 파괴하면 사다리를 생성하는 돌(정확히는 타일)을 할당하는 기존의 레트로 보물방 사다리 생성 알고리즘과는 달리, 이 장신구는 그냥 아무 돌이나 파괴할 때 사다리가 생성되는 확률이 추가되는 알고리즘이다. 스테이지 시작 시 파괴하면 사다리를 생성하는 돌(정확히는 타일)을 할당하는 기존의 레트로 보물방 사다리 생성 알고리즘과는 달리, 이...",
    "game_id": "74"
  },
  {
    "id": 763,
    "type": "trinket",
    "name": "오류",
    "english_name": "Error",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/wsPFsi5IsVtoDad71LuxN5CNTQ2KEPEua_VOvWegrxj8bDZbiGbDNFoiRDMGNXryy_AFfv5Ap-3Xl7Uxu4MaUw.webp",
    "description": "효과를 찾을 수 없습니다?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방마다 다른 종류의 장신구 /황금 장신구의 효과가 적용된다. 어떤 장신구인지는 따로 표기되지 않기 때문에 플레이어가 직접 알아내야 한다. 결정된 장신구는 방마다 '귀속' 되어 있어 다른 방에 나갔다 들어와도 해당 방에서 결정된 장신구의 효과가 바뀌지는 않는다. 이 때 소모성 장신구들의 효과가 귀속되어 있어도 효과는 해당 방 내에서 계속 지속되기 때문에, 다음과 같은 현상이 일어난다.상점에서 Store Credit 장신구의 효과가 적용되거나 악마...",
    "game_id": "75"
  },
  {
    "id": 764,
    "type": "trinket",
    "name": "포커 칩",
    "english_name": "Poker Chip",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/xbefhQk9MnphsQDHXtKEPlulLrz7oJk0tH2vFXb8CnI3rBOb0EUGIveSYP9wz-xen0sZa3AZkFxK0Z5sNWB_zg.webp",
    "description": "더블 다운할 시간이다!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "50대 50의 확률로 상자에서 픽업 아이템(하트, 동전, 폭탄, 열쇠) 을 드랍하는 상자들에서 보상이 더 많이 나오거나보상 대신 빨간 파리 하나가 튀어나온다.빨간 상자, 오래된 상자에는 효과가 없다.거대 상자의 경우 픽업 아이템을 드랍할 때 빨간 파리가 섞여서 등장한다. 빨간 상자, 오래된 상자에는 효과가 없다.",
    "game_id": "76"
  },
  {
    "id": 765,
    "type": "trinket",
    "name": "블리스터",
    "english_name": "Blister",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/LgIkRdUyqJe_Y3mwJRWgb_xWaQobJwlF-_QmRhBMP-XFQEmrjvC1k_lBvcMVn5TQv5FTEQ-W8D3AZOJKb_JFxQ.webp",
    "description": "사라져라!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "눈물의 넉백을 증가시킨다.황금 Blister나, Mom's Box 소지 시 넉백이강해진다/더 강해진다. 황금 Blister나, Mom's Box 소지 시 넉백이강해진다/더 강해진다.",
    "game_id": "77"
  },
  {
    "id": 766,
    "type": "trinket",
    "name": "초침",
    "english_name": "Second Hand",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/rm9sW-g5BsiuNWOjxBLL7DMzwEfEw3yyLDZ2bIoQZkev4vsyG8d6lHrBw3s3kEN98ukb90ZFhGnWt2fhDukk1w.webp",
    "description": "효과 지속 시간 증가!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "아이템으로 부여되는 상태이상 효과의 지속시간을 2배 /3배/4배로 증가시킨다.",
    "game_id": "78"
  },
  {
    "id": 767,
    "type": "trinket",
    "name": "엔들리스 네임리스",
    "english_name": "Endless Nameless",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/uL8J7Qaz6Z0P2pAZNAJS4fMCI5Ei3UwbwBVFpSNaqWc56pejy1Y5b1yX_x0nuECAzP44FV1f1zAxbtlJ1yvIMw.webp",
    "description": "루프에 열중하고 있어...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "카드, 알약, 룬을 사용했을때, 25% /33%/50%확률로 사용한 픽업이 필드에 드랍된다.황금 알약의 경우는 사용할 때마다 장신구의 효과가 발동될 수 있는데, 당연히 황금 알약이 드랍된다. 황금 알약의 경우는 사용할 때마다 장신구의 효과가 발동될 수 있는데, 당연히 황금 알약이 드랍된다.",
    "game_id": "79"
  },
  {
    "id": 768,
    "type": "trinket",
    "name": "검은 깃털",
    "english_name": "Black Feather",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/oyw7MB1SICE0ptiu1azzLAHE1Av5r-VP-HghcKNQQtswdEtp171pk-AaTHRw6yMi4HLpXfRlRYACkObEV_RrxA.webp",
    "description": "어둠과 함께라면 힘이 오리라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "하단의 목록에 존재하는 아이템/장신구를 소유하고 있으면 개당공격력이 0.5 /1/1.5올라간다. Goat Head를 제외하면 획득시 Evil Up이나 Sin Up이라는 문구가 등장하는 아이템들이다. 해당하는 아이템/장신구 목록AbaddonBlack CandleBlack LipstickCeremonial RobesDaemon's TailFalse PHDGoat HeadMatch BookMissing PageSafety Pin",
    "game_id": "80"
  },
  {
    "id": 769,
    "type": "trinket",
    "name": "눈 먼 분노",
    "english_name": "Blind Rage",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/P_FCorcC9jN1iCvPdi2sRafpjjY3ec26P-g_2FfG9XOksA_2iT4nL55kShAmY5PXKqsGvRDtpSRo9R_kIeMC1w.webp",
    "description": "눈에 뵈는 게 없다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 후 무적 시간이 2배 /3배/4배가 된다.무적 시간 동안에는 헌혈 기계, 악마 거지 이용이 아예 봉인되기 때문에, 저 둘에는 활용할 수 없다. 무적 시간 동안에는 헌혈 기계, 악마 거지 이용이 아예 봉인되기 때문에, 저 둘에는 활용할 수 없다.",
    "game_id": "81"
  },
  {
    "id": 770,
    "type": "trinket",
    "name": "황금 말 신발",
    "english_name": "Golden Horse Shoe",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/7JSqS0z8FcrINVD5oqgMEulq59125H2w60SHywlPwymArqTLOibnIbXT_SS18H2BUzOjdBXTnbQA6TvXssIiiA.webp",
    "description": "운 좋은 것 같아?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "습득 후 다음 층부터 15% /30%의 확률로 보물방에 하나만 고를 수 있는 선택형 아이템이 두 개 배치된다.",
    "game_id": "82"
  },
  {
    "id": 771,
    "type": "trinket",
    "name": "상점 열쇠",
    "english_name": "Store Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/YULrhc7F76UGwM1nLpK7IdR2f7C2hlF4J1V2xp4p7EG1iEA9YqYO3y23Ar0UbsvkLvNJVp5KzuYmhxnHotg30Q.webp",
    "description": "상점은 언제나 열려 있습니다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "들고 있는 동안 모든 상점 문을 열 때 열쇠를 소모하지 않는다.Pay To Play를 획득해서 상점 문이 동전을 요구하도록 변경된 경우에는 효과가 없다. Pay To Play를 획득해서 상점 문이 동전을 요구하도록 변경된 경우에는 효과가 없다.",
    "game_id": "83"
  },
  {
    "id": 772,
    "type": "trinket",
    "name": "탐욕의 늑골",
    "english_name": "Rib of Greed",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/GkcdylxERkXJlcD6T8_5dQN1mY4nmjtwEetwUt2TlIBhgnNVeFumI9NgSrY6H__9nuPNyUziI0piF_TBj8zQEw.png",
    "description": "탐욕스러워",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "상점과 비밀방에서 Greed 미니보스와 Super Greed 미니보스가 등장하지 않게 된다. Greed 미니보스와 Super Greed 미니보스를 처치한 후 장신구를 획득하고 다시 가보면 본래의 상점이나 비밀방으로 돌아온다.",
    "game_id": "84"
  },
  {
    "id": 773,
    "type": "trinket",
    "name": "업보",
    "english_name": "Karma",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/m9174SW3Fqa3K9GwGj-mVVLq2dkOMD1wZoH_q5eIT3tPuN4gKK7ugX5cNJuB-oMqjQLJBGgY-K-nsBMNiXk9tw.webp",
    "description": "업보 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "기부 기계에 기부할 때마다 확률적으로 다음의 효과를 얻는다.빨간 하트 체력을 1칸 회복한다.거지를 소환한다.동전 1개를 즉시 획득한다. 기부한 동전을 돌려받는다고 보면 된다.행운+ 1/+ 2/+ 3. 기부 기계 자체적으로 가지고 있는 기부시 확률 행운 증가와는 별개로 계산된다. 빨간 하트 체력을 1칸 회복한다.",
    "game_id": "85"
  },
  {
    "id": 774,
    "type": "trinket",
    "name": "리틀 라바",
    "english_name": "Lil Larva",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/29PktevLMFW-NFPBsigCK6mMAfPVqHvAxD8ST9_JjYezRICL7yKWnf_98pvWTzj2AklUn3WiZ-mOuFLPQ_UX4w.webp",
    "description": "응아가 움직여",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "똥이 파괴될 때마다 아군 파리가 1마리 /2마리/3마리생성된다.아쉽게도 빨간 똥은 파리를 생성하지 않는다. 아쉽게도 빨간 똥은 파리를 생성하지 않는다.",
    "game_id": "86"
  },
  {
    "id": 775,
    "type": "trinket",
    "name": "엄마의 심장",
    "english_name": "Mom's Locket",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/1vANRYnW_awCfKsFy7QYN0dlD5H-EkeAbb_TOQg09ibnhZdRUniI6EyA-sze9KwGRp1JHbTQu0vT-Ky96tWXuQ.webp",
    "description": "엄마의 사랑이 느껴집니다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "열쇠를 소모할 때마다 빨간 하트 체력 반 칸 /한 칸/한 칸 반을 회복한다.열쇠를 소모해야 하기 때문에 황금 열쇠를 가지고 있거나 Paper Clip을 흡수한 상태면 이 장신구가 동작하지 않으므로 주의.(더럽혀진) 키퍼의 체력도 회복시킬 수 있으며 더럽혀진 베다니의 경우는 빨간 하트 게이지가 차오른다. 열쇠를 소모해야 하기 때문에 황금 열쇠를 가지고 있거나 Paper Clip을 흡수한 상태면 이 장신구가 동작하지 않으므로 주의.",
    "game_id": "87"
  },
  {
    "id": 776,
    "type": "trinket",
    "name": "아니!",
    "english_name": "NO!",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/FeH_-hW19qWwSA0QiOUrQCK9ILhh8UB7EdTrG7VxQLdszcchj-of82hVnEI_sIdRIOLPT_CTKk5VWmuBlytPTA.png",
    "description": "필요없어!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "들고 있는 동안 모든 방의 배열에서 액티브 아이템과 등급 0의 아이템이 등장하지 않게 된다.해당 방의 패시브 배열이 전부 다 소진되었더라도 Breakfast가 등장할 지언정 액티브 아이템은 등장하지 않는다.특정 보스 / 미니 보스가 드랍하는 액티브 아이템들도 얄짤없이 등장하지 않는다.기본적으로 Pony / White Pony를 드랍하는 A Headless Horseman / Couquest는 이 장신구를 든 채 잡으면 다른 묵시록의 4기사들처럼...",
    "game_id": "88"
  },
  {
    "id": 777,
    "type": "trinket",
    "name": "갈색 마개",
    "english_name": "Brown Cap",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/DoqZUIl1FuJ2y7K8T_tPEsnykAECTfl7RvDbcotKjyVNKHO3XJXPwfqNLYV_oWYs5H-RnA6E2Lo5K1DpeM0Y1A.webp",
    "description": "뿌릉쾅",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "똥을 파괴할 경우 폭발을 일으키며 주변의 적에게 100 /200/300의 피해를 준다.폭발 관련 시너지가 적용되지 않는다.붉은 똥은 폭발하지 않는다. 폭발 관련 시너지가 적용되지 않는다.",
    "game_id": "90"
  },
  {
    "id": 778,
    "type": "trinket",
    "name": "태변",
    "english_name": "Meconium",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/4i7ehyFgyBbTIyoQfrcivI4XRoVULugXbQO9arSvRZnFCHlRT5MzDbSfc5u7JmDfj7-2iHdvqzR9RrkweCtUnw.webp",
    "description": "우웩",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "앞으로 등장하는 똥들이 33% /66%/100%확률로 검은 똥으로 대체된다.자연적으로 생성된 빨간 똥들도 검은 똥으로 변할 수 있다. 자연적으로 생성된 빨간 똥들도 검은 똥으로 변할 수 있다.",
    "game_id": "91"
  },
  {
    "id": 779,
    "type": "trinket",
    "name": "금이 간 왕관",
    "english_name": "Cracked Crown",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/XdEjX4648sH74zwVm0u5x_SM8BO7gnQmplt-4HT5J0ZUB39wVznHxwSRvlg-omcOggJ6yNGjDwfnREJAlI6TiQ.png",
    "description": "스탯 부스팅",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터의 이동 속도, 공격력, 공격 속도, 사거리, 눈물 속도가 각각 캐릭터의 기본 능력치보다 높을 경우 해당 능력치가(현재 능력치 - 기본 능력치) × 0.2 /0.4/0.6만큼 증가한다.예를 들어, 일반 Cracked Crown 기준으로 기본 공격력이 3.5인 캐릭터의 공격력이 1 올라 4.5일 경우, 4.5에서 20%가 증가하는 것이 아닌, 추가 공격력 1이 20% 증가되어 추가 공격력이 1.2가 되고, 최종적으로 캐릭터의 공격력은 4.7...",
    "game_id": "92"
  },
  {
    "id": 780,
    "type": "trinket",
    "name": "사용한 기저귀",
    "english_name": "Used Diaper",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/u2SX3vGK83q-8FRuEEGcL--PILrBrnF1ZyBIUzuCxosi-nMw8vym32vJHtJDzSDTDl9G1DdsdKNhhfbAr8Aanw.webp",
    "description": "냄새 나",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "장신구를 가지고 있을때 방에 입장시 33% 확률로 Skatole의 효과가 적용된다. 자세한 설명은Skatole 아이템 항목으로.확률은 행운 수치와 관련이 없다.장신구를 내려놓았을 경우 파리들이 다시 공격적으로 변하나, 이미 검은 파리로 변한 파리들은 돌아오지 않는다. 확률은 행운 수치와 관련이 없다.",
    "game_id": "93"
  },
  {
    "id": 781,
    "type": "trinket",
    "name": "생선 꼬리",
    "english_name": "Fish Tail",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/w2DcmKsaAgmQ7w6B1jPYqSiruewlGRKlylLZsrsOLlcmec5URm3IcUtZwJOSvXkgTDzBwldXjpWzXDlTzHFQyg.webp",
    "description": "이것도 냄새 나!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "아군 파리가 생성될 때, 20% 확률로 2배 /3배/4배의 파리가 생성된다. Fish Tail의 효과를 적용받는 아이템/장신구빨간 상자에서 나오는 아군 파리썩은 하트Berkano 룬Fish HeadFriends Till The End! 알약Guppy's Head 및 Guppy 변신Jar of FliesInfectionLil LarvaLil PortalLocust of XXX 장신구Mom's UnderwearThe MulliganRotten Pe...",
    "game_id": "94"
  },
  {
    "id": 782,
    "type": "trinket",
    "name": "검은 이빨",
    "english_name": "Black Tooth",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/VnMIdf38oO1rtY_HRk8TMtvQVtpZYPOaPbspvDrwlGIoHVetP1u9tUZvyqKBC-afcVbblBzDQY6VXP944NNRyw.webp",
    "description": "죽은 것 같은데",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 일정 확률로 적을중독시키는 검은 이빨이 발사된다.검은 이빨의 대미지는 현재 눈물 공격력의 2배이다. 검은 이빨의 대미지는 현재 눈물 공격력의 2배이다.",
    "game_id": "95"
  },
  {
    "id": 783,
    "type": "trinket",
    "name": "꼬리를 문 벌레",
    "english_name": "Ouroboros Worm",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ilNWs66JIzW3dzXYvEGGLwPZFmfckDJYi71HF7DW5Z3_mg0Aaf1t6MT3Szug93XaiOeapNiMICqJXTKWUc32mQ.webp",
    "description": "슝슝 날아간다!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 속도+ 0.4/+ 0.8/+ 1.2 사거리+ 1.5/+ 3/+ 4.5",
    "game_id": "96"
  },
  {
    "id": 784,
    "type": "trinket",
    "name": "편도선",
    "english_name": "Tonsil",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/qOXoQSFLcMofA1iCnwr8CTqqUUE76dlxU7rH-n71tB3ZuECOFuMh9BcSC1ViMW5ZuGpokVZnT-UmIpRtphJJcg.webp",
    "description": "아파...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터가 6 ~ 12번 피격을 당하면 Tonsil 패밀리어가 생성되어 캐릭터 뒤를 따라오며, 적의 발사체를 막는다.성공적으로 2개 /3개/4개를 소환했다면 장신구가 소멸한다. 성공적으로 2개 /3개/4개를 소환했다면 장신구가 소멸한다.",
    "game_id": "97"
  },
  {
    "id": 785,
    "type": "trinket",
    "name": "콧물딱지",
    "english_name": "Nose Goblin",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/bJ2bSqKFDlmev4S1JEZf5dqVI-z1XYJWWDiMtIbU9rXba8PFXlGwY6qR8EMUoI8GV3mL8bXuaemPMJ_e_WwNFQ.webp",
    "description": "마술처럼 보이는걸...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 10% /20%/30%확률로 적에게 달라붙어 중독시키는 코딱지를 발사한다. 코딱지에 대한 자세한 설명은Sinus Infection 아이템 항목으로. 이 장신구 및 Sinus Infection으로 발사되는 코딱지가 50% /75%/100%확률로 적에게유도된다.",
    "game_id": "98"
  },
  {
    "id": 786,
    "type": "trinket",
    "name": "탱탱볼",
    "english_name": "Super Ball",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/IJKktxKD3LlLrqYrGgPugFy3YQgrzdLh6Tf_3bam0UU6Sy0ng-zkezNr5sTez2EIA3Bx1MJbXO7Q65UTcGkMAg.webp",
    "description": "띠용!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 일정 확률로 Rubber Cement처럼 벽이나 적에 튕겨져 나오는 눈물을 발사한다. Rubber Cement가 적용된 눈물을 발사할 확률은 행운에 비례한다. 기본 확률은 10% /20%/33%이며 행운이 8 이상일 때 100% 확률로 발동된다.",
    "game_id": "99"
  },
  {
    "id": 787,
    "type": "trinket",
    "name": "밝은 전구",
    "english_name": "Vibrant Bulb",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/LJ4Y1su4Q6eVgq5WnsV56yzC8RRuXbNe7LdFAlO4CFlBbGVq8E-yTY-6xqIv2ylvaa1e_b-ob5SM7yCIdqCmhA.webp",
    "description": "전력이 필요해",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 중인 액티브 아이템의 게이지가 전부 차 있을 경우 하단의 스탯 보너스를 얻는다.이동 속도+ 0.25/+ 0.5/+ 0.75공격력+ 0.5/+ 1/+ 1.5공격 속도+ 0.2/+ 0.4/+ 0.6사거리+ 0.75/+ 1.5/+ 2.25눈물 속도+ 0.1/+ 0.2/+ 0.3행운+ 1/+ 2/+ 3 이동 속도+ 0.25/+ 0.5/+ 0.75",
    "game_id": "100"
  },
  {
    "id": 788,
    "type": "trinket",
    "name": "어두운 전구",
    "english_name": "Dim Bulb",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/96rfHvAEMYQBo-MxqQ5H-SbVxkXX3ZQBrdrRdXUPrnfwm78fq37LWdXSFnWSr5h7aBLITCBb6zYM8tyStI6o6w.webp",
    "description": "망가진 것 같아",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 중인 액티브 아이템의 게이지가 하나도 없는 경우 하단의 스탯 보너스를 얻는다.이동 속도+ 0.5/+ 1/+ 1.5공격력+ 1.5/+ 3/+ 4.5공격 속도+ 0.5/+ 1/+ 1.5사거리+ 1.5/+ 3/+ 4.5눈물 속도+ 0.3/+ 0.6/+ 0.9행운+ 2/+ 4/+ 6 이동 속도+ 0.5/+ 1/+ 1.5",
    "game_id": "101"
  },
  {
    "id": 789,
    "type": "trinket",
    "name": "조각난 카드",
    "english_name": "Fragmented Card",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/VPlEbbu0isJcAOlV5TTfws1OQvBI_mIHol44qyjesyAXDgzuQxmgjHRFcCkXpcUw4n1nQGLT9uYe2C-c3HSyjQ.webp",
    "description": "달이 두 배로",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지한 이후 스테이지를 시작할 때 비밀방이 두 개 생성된다.일단 생성된 추가 비밀방은 장신구를 버려도 사라지지 않는다.일급 비밀방은 추가 생성되지 않는다. 일단 생성된 추가 비밀방은 장신구를 버려도 사라지지 않는다.",
    "game_id": "102"
  },
  {
    "id": 790,
    "type": "trinket",
    "name": "등호!",
    "english_name": "Equality!",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/_Ib_UItD2BiNsvD0vgmQHH-jkzK-O6XjRngvXrphinEgrnLWj4_xOv5J0fWKlklWVli15c-nDtSUsUwjNb7BWw.webp",
    "description": "=",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "가지고 있는 동전, 폭탄, 열쇠의 개수가 모두 같을때 나오는 픽업 아이템들이 1+1로 두 개 붙어서 나오며,공격 속도가+ 2/+ 4/+ 6증가한다.이 공격 속도 증가는 한계치를 초과할 수 있다.특정 아이템, 캐릭터가 생성하는 반짝이는 픽업 아이템들도 효과를 받아 1+1로 나오며, 이 픽업 아이템들은 사라지지 않는다.조건만 맞으면 현재 있는 픽업 아이템들도 즉시 효과를 보게 되며 붙어서 나온 템은 장신구 효과가 해제되어도 다시 하나로 되돌아가지 ...",
    "game_id": "103"
  },
  {
    "id": 791,
    "type": "trinket",
    "name": "창사골",
    "english_name": "Wish Bone",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/uo-RePP2uvSnMhz--mT17XD2eHM2Qp18BRwO4Q0IGIaQtNOEYOGOgAlDOWcMZcNb4j7Quj_gSQT9DnNri4oqUA.webp",
    "description": "창의적인 사람에게 있는 뼈",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 5% /10%/15%확률로 장신구가 파괴되고 현재 방에 맞는 배열의 랜덤 아이템이 하나 나온다.",
    "game_id": "104"
  },
  {
    "id": 792,
    "type": "trinket",
    "name": "점심 도시락",
    "english_name": "Bag Lunch",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/VQRN1WlXE8RNPMjZCOdf_YEHRx1levzOExfm8xRpPyWfZ6yluo37FoIZ9MnqNd57B0MPQ-dxAlGavUQMVrVduw.webp",
    "description": "뭐가 들어 있을까",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 5% /10%/15%확률로 장신구가 파괴되고 패시브 아이템 Lunch가 나온다.",
    "game_id": "105"
  },
  {
    "id": 793,
    "type": "trinket",
    "name": "잃어버린 코르크",
    "english_name": "Lost Cork",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/kS9LkVzefXRWOlWs_VXQUvEs5Pm7MRGRl9fkxOhpGWFxMfIWga7Hhy-Uxs4RbAS5RlJLbbeToj6krttrz3pU9A.webp",
    "description": "따인 코르크",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터와 패밀리어가 생성하는 장판류의 범위가 약 1.5배 /2배/2.5배늘어난다.",
    "game_id": "106"
  },
  {
    "id": 794,
    "type": "trinket",
    "name": "까마귀 심장",
    "english_name": "Crow Heart",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/SKVlfzh5ZXq03XcZQAetSv3Fvp4MyqFmTetJ8fmoZIMDqxk0_taq3GGfkv2z72McbMfPNzpNaQTn3NiWUKF7kg.webp",
    "description": "나를 흡수해 줘",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 소울 하트, 블랙 하트, 썩은 하트 대신 빨간하트가 먼저 소모되게 된다.이로 인해 소울/블랙 하트가 있어도실수로 인한 피격을 당하면 악마방/천사방 등장 확률이 감소하게 되는데, 0% /25%/50%의 확률로 악마방/천사방 등장 확률이 감소하지 않는다. 이로 인해 소울/블랙 하트가 있어도실수로 인한 피격을 당하면 악마방/천사방 등장 확률이 감소하게 되는데, 0% /25%/50%의 확률로 악마방/천사방 등장 확률이 감소하지 않는다.",
    "game_id": "107"
  },
  {
    "id": 795,
    "type": "trinket",
    "name": "호두",
    "english_name": "Walnut",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ZfbWWfCWo3dD1a1lBT-uw9hDJcLoMrudFaP3__XcjzMNm-SEdjdQ4Dos2sxJAn-tS-IgqlgXN3WWWGcRYOtBkA.webp",
    "description": "단단한 녀석이구만!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "폭발에 휘말릴 시 33% 확률로 장신구가 파괴되고 무작위 동전, 하트, 열쇠, 장신구를 하나 /둘/셋씩 드랍한다.폭발에휘말리는게 조건이지 폭발에 휘말려피격을 입는 게 조건이 아니기 때문에 무적 상태에서 폭발에 휘말리거나 Host Hat, Pyromaniac이 있어도 장신구 효과는 발동된다. 폭발에휘말리는게 조건이지 폭발에 휘말려피격을 입는 게 조건이 아니기 때문에 무적 상태에서 폭발에 휘말리거나 Host Hat, Pyromaniac이 있어도 장...",
    "game_id": "108"
  },
  {
    "id": 796,
    "type": "trinket",
    "name": "청테이프",
    "english_name": "Duct Tape",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/rIqnmx_zglDxGAzM-_legKl6WkA4m1dRLQfWbZ9x354R9cZjJ1znXmj8tdUrVHvyLtLbi_pch18TfwEJoY0dow.webp",
    "description": "딱 붙어라!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터를 중심으로 움직이는 패밀리어들의 위치를 습득한 시점으로 고정한다.떨어뜨렸다가 다시 주우면 패밀리어들의 위치를 옮길 수 있다.일부 패밀리어는 영향을 받지 않는다. 주요 시너지 효과 항목 참고. 떨어뜨렸다가 다시 주우면 패밀리어들의 위치를 옮길 수 있다.",
    "game_id": "109"
  },
  {
    "id": 797,
    "type": "trinket",
    "name": "은화",
    "english_name": "Silver Dollar",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/VngpkAu2pAvXDZ8uRCO8Gk8cgOVerEbJVshpo8Dr0A7WfxiBvfnZsTKOPIODaQ6r3k-7CEAlzc8YtqRo075mnw.webp",
    "description": "운이 좋은 기분...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Womb / Utero / Scarred Womb / Corpse를 이 장신구를 소지한 채 시작하면 스테이지에 상점이 생성된다.황금 Silver Dollar나, Mom's Box 소지 시높은 등급의 상점이 보장된다.당연히 (Super) Greed가 생성될 수 있다. 황금 Silver Dollar나, Mom's Box 소지 시높은 등급의 상점이 보장된다.",
    "game_id": "110"
  },
  {
    "id": 798,
    "type": "trinket",
    "name": "피투성이 왕관",
    "english_name": "Bloody Crown",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/RpJJa_e-TpMPSxJ8FgMgmHajKagbFO1FELSXBGS5sbSE6vFUMgnbST2tTMVUfPyf-fDg1b0tLxnXGL62eglI9g.webp",
    "description": "피가 뚝뚝 떨어져...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Womb / Utero / Scarred Womb / Corpse를 이 장신구를 소지한 채 시작하면 스테이지에 보물방이 생성된다.Curse of Labyrinth 저주에 걸렸다면 2개가 생성된다.황금 Bloody Crown이나, Mom's Box 소지 시More Options가 적용된 보물방이 생성된다.Corpse 스테이지의 경우 다른 대체 루트 스테이지처럼 선택형 아이템 2개를 제시하며, 이 중 하나는 Curse of the Blind에 걸린...",
    "game_id": "111"
  },
  {
    "id": 799,
    "type": "trinket",
    "name": "지갑 전사",
    "english_name": "Pay to Win",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/wh4AIEhO7COHqaC16p817G5OtzhYXFaQEuDMsWxC8v6H5DR2Nk-mgVSDQv1ZcQilAq8qTp57fPaoMI34Vc4CzQ.webp",
    "description": "...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "이 장신구를 소지한 채 스테이지를 시작하면 스테이지의 보물방에 리스톡 기계가 생성된다.그리드 모드에서는 일반 보물방은 물론, 은색 보물방에도 리스톡 기계가 생성된다.???(Hush 스테이지)의 보물방, Home 루트로 진입하던 도중에 나오는 이미 열려있는 보물방, 거울 세계의 Knife Piece I을 얻을 수 있는 보물방에는 생성되지 않는다. 그리드 모드에서는 일반 보물방은 물론, 은색 보물방에도 리스톡 기계가 생성된다.",
    "game_id": "112"
  },
  {
    "id": 800,
    "type": "trinket",
    "name": "전쟁의 메뚜기",
    "english_name": "Locust of War[39]",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/pvQGq51TkR6A9DZVZRmihKAFIgE_SxkJx8-HyoEFI2Fpnee0ova7PP6mrRo9dxS5r4x1eNZ2G5vqPeUYj6eavA.webp",
    "description": "전쟁을 초래",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면 오렌지색 파리가 1마리 /2마리/3마리생성된다. 이 파리는 적에게 날아가 캐릭터의 공격력의 두 배만큼의 피해를 주며 동시에 폭발해 주변의 적에게 60의 피해를 준다.보스 러쉬에선 매 웨이브마다 생성된다.이 폭발은 대부분의 폭탄 시너지를 적용받는다. 보스 러쉬에선 매 웨이브마다 생성된다.",
    "game_id": "113"
  },
  {
    "id": 801,
    "type": "trinket",
    "name": "역병의 메뚜기",
    "english_name": "Locust of Pestilence",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Eh4Axk2ql2en_nlf1KhGeXHHbah39cViC_SOB31QTyVP6tlCRjElozQRD-kb_mkOkgQOBcBQ_1z8MoKa0rFaZw.webp",
    "description": "역병을 초래",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면 초록색 파리가 1마리 /2마리/3마리생성된다. 이 파리는 적에게 날아가 캐릭터의 공격력의 두 배만큼의 피해를 주며 동시에 그 적을중독시켜 총 캐릭터의 공격력만큼의 대미지를 2번 입힌다.보스 러쉬에선 매 웨이브마다 생성된다. 보스 러쉬에선 매 웨이브마다 생성된다.",
    "game_id": "114"
  },
  {
    "id": 802,
    "type": "trinket",
    "name": "기근의 메뚜기",
    "english_name": "Locust of Famine",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/dA8vyi3yAIN--d_iLeOkYz47qmxmTslKlhsdFUgkIRm89Hu2xZH0tvxFlgR3nKONmUm5WBdp7FK1UEGQDZiYDQ.webp",
    "description": "기근을 초래",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면 노란색 파리가 1마리 /2마리/3마리생성된다. 이 파리는 적에게 날아가 캐릭터의 공격력의 두 배만큼의 피해를 주며 동시에 그 적에게둔화상태이상을 건다.보스 러쉬에선 매 웨이브마다 생성된다. 보스 러쉬에선 매 웨이브마다 생성된다.",
    "game_id": "115"
  },
  {
    "id": 803,
    "type": "trinket",
    "name": "죽음의 메뚜기",
    "english_name": "Locust of Death",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/0Au2JXNQGJIinCjnT46SSjYfQs6Uvl8JjoxLGbm6fOtteDC_P7algcK6K3RPmYcpU9XAM2EdBGTz6lkOVWavZw.webp",
    "description": "죽음을 초래",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면 검은색 파리가 1마리 /2마리/3마리생성된다. 이 파리는 적에게 날아가 캐릭터의 공격력의 두 배만큼의 피해를 두 번 준다.보스 러쉬에선 매 웨이브마다 생성된다. 보스 러쉬에선 매 웨이브마다 생성된다.",
    "game_id": "116"
  },
  {
    "id": 804,
    "type": "trinket",
    "name": "정복의 메뚜기",
    "english_name": "Locust of Conquest",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ekKAx6d0PtR5dgij8P2pGOkiczkdug_qXFs0_gydrlez_3LIGGM3qVjX59pS7gOw-KT952r-Uh-AkqvLtXp0Lw.webp",
    "description": "정복을 초래",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면 하얀색 파리 1~4마리 /2~5마리/3~7마리가 생성된다. 이 파리는 적에게 날아가 캐릭터의 공격력의 두 배만큼의 피해를 준다.보스 러쉬에선 매 웨이브마다 생성된다. 보스 러쉬에선 매 웨이브마다 생성된다.",
    "game_id": "117"
  },
  {
    "id": 805,
    "type": "trinket",
    "name": "박쥐 날개",
    "english_name": "Bat Wing",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/v4fgm4Be9kAucjpNzAXqqhMaXkruR2GDx71NEin_P1Ma7REHPt1-EKw8znATUyIR2FlvxH-UNhATDJee86QEzQ.webp",
    "description": "자라는 것 같은데...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적을 처치 시 5% /10%/15%확률로 캐릭터에게 박쥐 날개가 생기며 그 방에서만비행효과를 얻는다.",
    "game_id": "118"
  },
  {
    "id": 806,
    "type": "trinket",
    "name": "줄기세포",
    "english_name": "Stem Cell",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/_9WSTxDhqGB4HyHWxNNL2iLi4UBuY0QtqeP2EjvOrO2G6nk14kev58XlaGejOixT1Z7rvHxyygmjlayP1r3Duw.webp",
    "description": "회복되어라!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "다음 층으로 내려갈 때 빈 빨간 하트 체력이 있다면 다음 층에서 비어있는 체력의 절반에 해당하는 체력이 /비어있는 체력이 전부회복된다.일반 장신구의 경우 Mom's Box가 없을 때 이미 빨간 하트 체력이 절반 이상 차 있었다면 빨간 하트 반 칸을 회복한다.빈 뼈 하트에도 적용된다. 일반 장신구의 경우 Mom's Box가 없을 때 이미 빨간 하트 체력이 절반 이상 차 있었다면 빨간 하트 반 칸을 회복한다.",
    "game_id": "119"
  },
  {
    "id": 807,
    "type": "trinket",
    "name": "머리핀",
    "english_name": "Hairpin",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/iZvPcZ8TqYhJtzVFL8LFMyPEu3rVUq6EdD9KXYDs-HxfO2E08LP0Tk51oxiVBVICxOJdmaeudNnrSFcyK5YXgw.webp",
    "description": "위험한 충전",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "보스 방에 처음 진입 시 액티브 아이템의 충전 게이지를 전부 /2회분만큼채워준다.Corpse II에서는 보스 방에 처음 입장할 때 한 번, Mother 보스와의 전투 시 한 번으로 총 두 번 충전된다.Dogma에서 The Beast로 넘어갈 때는 충전되지 않는다.그리드 모드에선 Ultra Greed 전에서만 적용된다. Corpse II에서는 보스 방에 처음 입장할 때 한 번, Mother 보스와의 전투 시 한 번으로 총 두 번 충전된다.",
    "game_id": "120"
  },
  {
    "id": 808,
    "type": "trinket",
    "name": "나무 십자가",
    "english_name": "Wooden Cross",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/VDjw-0aYpeE9-lVzOaVBo1u2NvCz727IYhgzeIBbJN4UAl010_OgS5R3PTGMb-VbFX7jnaSQZlrSTJipekymAA.webp",
    "description": "내 믿음이 나의 방패라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "매 층마다 피격을 1회 /2회막아주는 보호막이 생성된다. 이 보호막은 모든 보호막들보다 우선시되는데피격되어 사라진 보호막은다른 방에 가도 재생성되지 않으며 이는 The Lost도 마찬가지이므로 주의.",
    "game_id": "121"
  },
  {
    "id": 809,
    "type": "trinket",
    "name": "버터!",
    "english_name": "Butter!",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/cg9ksqb6GX_WYWLc_f2BlEhzK6vJxqIVH4mp6zFH4MNWZZxRbxRuOqRMmc4k77i2MryLm2bv2BrfxDoIBwTRrA.webp",
    "description": "너무 미끄러워!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "액티브 아이템 사용 시 해당 액티브 아이템 효과를 발동시킨 후 주위에 받침대 형태로 내려놓는다.더럽혀진 캐릭터들이 알약/카드 슬롯에 소유하고 있는 액티브 아이템들은 사용으로는 내려놓지 않지만 피격시에는 내려놓을 가능성이 있는데 이 경우 다시 주우면 일반 액티브 아이템 슬롯을 차지하며 알트 \"Cain\"은 아이템으로 분해되니 이러한 캐릭터라면 사용을 자제하는 게 좋다.일부 아이템들은 효과 발동 전에 바로 내려놓는다. 목록은 하단의 주요 시너지 효과...",
    "game_id": "122"
  },
  {
    "id": 810,
    "type": "trinket",
    "name": "세공 깃털",
    "english_name": "Filigree Feather",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ebKX9YjG6CHmLoLuICMQYfGjYMt0HGbw6B5ifgQfPKABHM1CyTbH-axZN6uGxHOJdpRAIASMR6oN-zRfLbaQHg.webp",
    "description": "천사의 유물",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Key Piece를 드랍하는 천사 보스(Uriel, Gabriel)가 죽을 때 열쇠 조각 대신 다른 아이템을 내놓는다.Key Piece 1 혹은 2를 하나만 소유하고 있다면 열쇠 완성에 도움을 주기 위해 1회에 한해 획득하지 않은 Key Piece를 드랍한다.열쇠 조각을 드랍하지 않는 천사들은 아이템도 드랍하지 않는다. Key Piece 1 혹은 2를 하나만 소유하고 있다면 열쇠 완성에 도움을 주기 위해 1회에 한해 획득하지 않은 Key Pie...",
    "game_id": "123"
  },
  {
    "id": 811,
    "type": "trinket",
    "name": "문받침대",
    "english_name": "Door Stop",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/P92SVPbbKcM4gS673I96_apMVoLqWtHK-lC7GO3HiLlzM7jzxI15EVWUbMXIcHN_tMGbZK_PHHKnXal613C4mw.webp",
    "description": "문을 열어둬",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적이 있는 방에 입장하면, 들어온 문 /보스 러쉬 입구/도전방 문이 닫히지 않고 열려있게 된다.애초에 나갈 수 없는 Mom 보스 방과 같은 방에서는 당연히 나갈 수 없다. 애초에 나갈 수 없는 Mom 보스 방과 같은 방에서는 당연히 나갈 수 없다.",
    "game_id": "124"
  },
  {
    "id": 812,
    "type": "trinket",
    "name": "연장 코드",
    "english_name": "Extension Cord",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/_jIfNTtR9xJR-DW1dwrqLB4HMpl49gZoibjpBxsCc6oId5BWn0magtw54tZUGpBgJ0_lltVs-5znTYtI2RR6Gw.webp",
    "description": "충전된 친구들",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "모든 캐릭터와 패밀리어 사이에 대미지 6 /12/18의 황색 전류를 주고 받는다. 황색 전류는 거리나 오브젝트 제한이 없으며 그 일직선 상에 있는 적들은 전류 공격을 받는다.패밀리어가 많을수록 생겨난 패밀리어 순으로 전류를 주고 받는다. 패밀리어가 많을수록 생겨난 패밀리어 순으로 전류를 주고 받는다.",
    "game_id": "125"
  },
  {
    "id": 813,
    "type": "trinket",
    "name": "부식된 동전",
    "english_name": "Rotten Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/nfZYA7sAvFSEbu0qSfIuDwN1un2qupBvpaSZDhBUhIrqrUx7kCQmWs2MTrNf74QqOkf9Ytgd9wf5NrYc9w5bBg.webp",
    "description": "파리들의 화폐",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전을 획득할 때마다 아군 파리를 1마리2마리/3마리생성한다.",
    "game_id": "126"
  },
  {
    "id": 814,
    "type": "trinket",
    "name": "베이비-벤더",
    "english_name": "Baby-Bender",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/xZ-aNNwpYqLi1fBGsX1TS9rElyjYi5aOXmjHbgXukBo71RWm7maFWOgsqO_mnSqcbEP6H3_Iz5tzkCmIhInivg.webp",
    "description": "마법을 먹여 키워!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "무언가를 발사하는 모든 패밀리어들의 공격에유도/+ Brain Worm/+ Tape Worm(사거리 증가)속성이 붙는다.당연히 릴리스가 기본으로 소유하는 Incubus, 더럽혀진 릴리스가 기본으로 소유하는 Gello에도 적용된다. 당연히 릴리스가 기본으로 소유하는 Incubus, 더럽혀진 릴리스가 기본으로 소유하는 Gello에도 적용된다.",
    "game_id": "127"
  },
  {
    "id": 815,
    "type": "trinket",
    "name": "손가락뼈",
    "english_name": "Finger Bone",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/39RvNhH-9quGtRpAPU6CBW8SdWJ9NlA6qH_QdkGrSWPOuBAWnNvH2e1br1iEhkGGHD9WRVbL7y0Lt_j62HawtQ.webp",
    "description": "잘 부러질 것 같아",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "대미지를 입을 때 4% /8%/12%확률로 뼈 하트를 즉시 획득한다. 부스터 팩에서 추가된 장신구들 중 유일하게 모드 출신이 아니다.",
    "game_id": "128"
  },
  {
    "id": 816,
    "type": "trinket",
    "name": "눈깔사탕",
    "english_name": "Jawbreaker",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/EDipEbEIoJsG7c-cXvC2PqsrHbOqqlqlCJf8qgz0WuZ40MFn9eTk7C7AVPFdhGGTv9v4XFM8449HnGvVC3eGFQ.webp",
    "description": "절대 깨물어 먹지마",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Tough Love와 동일한 일정 확률 크리티컬 효과다. 자세한 설명은이 항목으로.기본 확률은 10% /20%/30%이다. 기본 확률은 10% /20%/30%이다.",
    "game_id": "129"
  },
  {
    "id": 817,
    "type": "trinket",
    "name": "씹은 펜",
    "english_name": "Chewed Pen",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/D46IDjrk10f9B8UB6mCcbOXrevLvWVv6k3ANc9-tWYcv72PHgOXwgy5_69CgPEz9O5eC5gz9hhcYFDqnItKBlw.png",
    "description": "잉크가 새네",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 확률적으로 2.5초 동안둔화상태이상을 부여하는 눈물을 발사한다. 발동 확률은 행운에 비례하여 공식은 1/(10 - 행운 × 0.5). 기본 확률은 10% /20%/30%이며 최종적으로 행운이 18 이상이면 100%의 확률로 특수 눈물을 발사할 수 있다.",
    "game_id": "130"
  },
  {
    "id": 818,
    "type": "trinket",
    "name": "축복받은 동전",
    "english_name": "Blessed Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/7ipZj_h39rdEzy2w_z2OD8bse_SCc4ycWr-HwLxJg6CEbFDNKh4zaQFfh7v-xQKCr9G3WvwWaDvAtWRBn4Hsbg.png",
    "description": "순수의 화폐",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 소울 하트 반 칸을 드랍한다. 동전의 가치에 따라 확률이 다르며 그 확률은 다음과 같다.페니(1코인): 16.6% /25%/30%1+1 페니(2코인): 30.5% /40%/50%니켈(5코인): 59.7% /70%/75%다임(10코인) : 83.3% /90%/100% 페니(1코인): 16.6% /25%/30%",
    "game_id": "131"
  },
  {
    "id": 819,
    "type": "trinket",
    "name": "깨진 주사기",
    "english_name": "Broken Syringe",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/IZkR1TcEBkGBJRQQXh3HYRbU9DAcDufkJ0dlNfNC7n4PtAzZjzN8wLAhAAjCRe1K4kaM7viiwMLsmXODdr3M6Q.png",
    "description": "무슨 약이 들어있었을까",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장할 때마다 25% /50%/100%확률로 무작위 주사기 패시브 아이템의 효과가 발동될 수 있다.Experimental Treatment가 걸렸을 경우 체력 수치에는 영향을 주지 않아 무작위 능력치 3개가 증가하고 2개가 감소한다. Experimental Treatment가 걸렸을 경우 체력 수치에는 영향을 주지 않아 무작위 능력치 3개가 증가하고 2개가 감소한다.",
    "game_id": "132"
  },
  {
    "id": 820,
    "type": "trinket",
    "name": "짧은 도화선",
    "english_name": "Short Fuse",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/rt_7owiH6xCF3VedROSRF6rPHGxc6_QMqtkirhLh3iKtnY_oXyHBFVWsA401jBuMAaOvGEpJtHPt-hQdEj-Veg.webp",
    "description": "폭발이 빨라져",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터가 설치한 폭탄이 터지는 시간이 1.5초에서 0.66초로 감소한다. 폭탄의 공격력이 15% /30%/50%증가한다.",
    "game_id": "133"
  },
  {
    "id": 821,
    "type": "trinket",
    "name": "대왕 콩",
    "english_name": "Gigante Bean",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/thlcO83fJ9IcPYK7guIlP9Af8IOTFEP6FmIbcbBjdwFFVGwdXr3j5rQXyfGHi-mAyGFr8TBS9monSj89ZuEbdQ.png",
    "description": "폭발적인 방귀",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적들의 방귀, 방귀 아이템들의 효과 범위가 어마어마하게 넓어진다.황금 Gigante Bean이나, Mom's Box 소지 시방귀류의 넉백이 아주 강해지며, 둘 다 소지 시혼란 상태이상을 건다. 황금 Gigante Bean이나, Mom's Box 소지 시방귀류의 넉백이 아주 강해지며, 둘 다 소지 시혼란 상태이상을 건다.",
    "game_id": "134"
  },
  {
    "id": 822,
    "type": "trinket",
    "name": "라이터",
    "english_name": "A Lighter",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/rpXziFalLo-wPgG2omzBQmE4t0k9efvbGXVcSWBqeil0WXYAQVUYnVxizA79nUVq8gvb0wCSW_1sEBqGJlaY-g.png",
    "description": "세상이 불타는 꼴을 봐라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장 시 일정 확률로 일부 몬스터들이화상상태이상에 걸린 채로 나타난다. 각각의 몬스터들이 화상에 걸릴 확률은 행운에 비례한다. 기본 확률은 20% /33%/50%이며 행운이 40 이상이면 모든 몬스터들이 화상 상태이상에 걸린 채로 나타난다.",
    "game_id": "135"
  },
  {
    "id": 823,
    "type": "trinket",
    "name": "부러진 자물쇠",
    "english_name": "Broken Padlock",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9VkQXD7qiFTIxWlBhagtyjjc7h57EBXjd2Wb19RI1Fr4aLEM3W8-A-fu9NH1rBsBlq1G0WZN8-jeL0E1t64JYg.png",
    "description": "폭탄은 만능 열쇠야",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "잠긴 대부분의 오브젝트 및 문을 폭발로 열 수 있다. 열 수 있는 오브젝트/문열쇠, 폭탄, 동전, 체력을 이용하여 여는 문(보물방, 상점, 오락실, 책방, 주사위방, 금고방, 천체관 등)거의 모든 상자(유령들린 상자, Home 스테이지의 엄마 방에 있는 Mom's Chest제외)A Strange Door(Home 루트를 가기위해 Depths/Necropolis/Dank Depths 2에 등장하는 문)닫힌 도전 방 문닫힌 보스 방 문",
    "game_id": "136"
  },
  {
    "id": 824,
    "type": "trinket",
    "name": "물망초",
    "english_name": "Myosotis",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/y8GKoHfpymuBi-r9hGcBEpPTON_gniSt0McXwRPo7ubDOPrxnzgqkhUZtlsQujpvzg7uc7-kYY6K_DJjfed5fg.png",
    "description": "나를 잊지 말아요",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "다음 층으로 내려갈 때마다 이전 층에서 획득하지 못한 픽업 아이템/장신구가 최대 4개 /6개/8개까지 시작 방에 등장한다.에러 방의 픽업은 등장하지 않는다.안티버스 시절에는 8개까지 등장했으나 리펜턴스로 정식 편입되면서 너프되었다. 황금 Myosotis 효과가 추가되면서 Mom's Box + 황금 Myosotis 동시 소지로 이 시절 성능을 재현할 수는 있게 되었다. 에러 방의 픽업은 등장하지 않는다.",
    "game_id": "137"
  },
  {
    "id": 825,
    "type": "trinket",
    "name": "눈물 부적",
    "english_name": "Teardrop Charm",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/LHUCpv4Xm6weSI5pdGzAmCsyqfbswrC5JFnkI97PGCENmqfZiEBIIY0mWS06J0jZEvf1MFsd-W4G9_smwnik_w.png",
    "description": "운이 좋은 것 같아",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "발동 확률이 행운에 비례하는 눈물 특수능력의 발동 확률이 + 4 /+ 6/+ 8행운만큼 증가한다.캐릭터의 공격 방식이 눈물이 아니거나, 행운 스탯이 적용되는 다른 부분에는 영향이 없다. 캐릭터의 공격 방식이 눈물이 아니거나, 행운 스탯이 적용되는 다른 부분에는 영향이 없다.",
    "game_id": "139"
  },
  {
    "id": 826,
    "type": "trinket",
    "name": "베다니의 믿음",
    "english_name": "Beth's Faith",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/1_AqjCs7Qt9zDQMXWR03-W5QH73u7auRhXCQTSIOFrxcU74ZDrXOiNWEwcH9axt0InJU3WWogMHBj2NehbtZzg.png",
    "description": "내 믿음이 나의 방패라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "스테이지를 시작할 때마다 Book of Virtues로 생성되는 위습 4개 /8개가 생성된다. Beth's Faith로 생성되는 위습은 최대 8개까지 생성된다.",
    "game_id": "142"
  },
  {
    "id": 827,
    "type": "trinket",
    "name": "낡은축전기",
    "english_name": "Old Capacitor",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Aa0zPdcxeWqSbrArmUPvx-4AxlmKfLdH5Mm60GNv7oTuokU0Tdila8HwBh7bG06oCT48tlx-DWiy4zuJZe0JSQ.png",
    "description": "전압에 굶주림",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방 클리어 시 더 이상 액티브 아이템 게이지가 차오르지 않는 대신 Lil' Battery가 드랍될 확률이 생긴다.Lil' Battery는 방 보상으로 생성되는 것이 아니기 때문에 방 보상과는 별개로 생성된다.드랍 확률은 행운에 비례하여 확률은 (20 + 3 × 행운)%. 최종적으로 행운이 5 이상이면 33% 확률로 방 클리어 시 Lil' Battery가 생성된다. 황금 Old Capacitor거나 Mom's Box를 소지 시33% 고정이다. L...",
    "game_id": "143"
  },
  {
    "id": 828,
    "type": "trinket",
    "name": "두뇌 벌레",
    "english_name": "Brain Worm",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/MgUtxZQu3S-DL6FxV69MF4MYXxXEp5qpr_sNXLBvjwuk3UVCEVqaoV5NloUuF7EL-DNNYiXCFRV4vnrBHMWPAg.png",
    "description": "띵!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터의 공격이 몬스터 옆을 지나갈 경우 90도로 꺾여서 몬스터에게 날아간다. 황금 Brain Worm이나, Mom's Box 소지 시 공격이25%/50%확률로 적을관통한다.",
    "game_id": "144"
  },
  {
    "id": 829,
    "type": "trinket",
    "name": "올백",
    "english_name": "Perfection",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/xPgTsqdOjeMjgtQU4Rut1H7Hl9cqdiHkl0kOOtLfVbkf4Nl6YOQw9CiR_wbBvI_IpzuP2omha62EMRSpK4lAww.png",
    "description": "Luck way up. Don't lose it!(운이 좋네. 그 행운을 잃지 말라구!))",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "행운+ 10/+ 20/+ 30 일반적인 드랍으로는 얻을 수 없고, 3개의 스테이지를실수로 인한 피격없이 클리어하면 3번째 스테이지의 보스 처치 시에 고정적으로 드랍된다. 황금 Perfection은 아이템 상태로는 자연적으로 얻을 수 없으며, 장신구를 흡수할 때 황금 상태로 흡수되는 거대 Gulp! 알약으로만 얻을 수 있다.",
    "game_id": "145"
  },
  {
    "id": 830,
    "type": "trinket",
    "name": "악마의 왕관",
    "english_name": "Devil's Crown",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/CJOVt1320gNbus6kP2CvcSsF886F9enc_zRMF3BTpZXlXaYcBO0mq5Et9UMlLnUIsaa4qX8YlwE93WuhONqWSw.png",
    "description": "특별 손님이 오셨네",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "장착 이후 나오는 보물 방이 빨간 보물 방으로 바뀌며, 보물 방 배열 아이템 대신 악마 방 배열 아이템을 체력 거래로 제시한다.황금 Devil's Crown이나, Mom's Box 소지 시 빨간 보물 방이25%/33%확률로 Number Magnet으로 생성되는 악마 방 구조로 나올 수 있다.당연히 거울 세계의 Knife Piece I을 얻을 수 있는 보물 방은 바뀌지 않는다.장신구를 떨구면 떨군 즉시 일반 보물 방으로 되돌아가고, 다시 주우면 ...",
    "game_id": "146"
  },
  {
    "id": 831,
    "type": "trinket",
    "name": "충전된 동전",
    "english_name": "Charged Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/z3DUKBb1YictpgBe38mFfR03ipNL-7t5g6ANd2VINey5aqtIMlcTGwhueQe6N561fhKuBMerHw98zlvd77K8lA.png",
    "description": "힘의 화폐",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전 픽업을 획득 시 일정 확률로 액티브 아이템 게이지를 1칸 /2칸/3칸채워준다.발동 확률은 해당 동전의 가치에 1/6을 한 값의 백분율이며, 10원짜리 동전인 다임은 10/6 = 1.666... = 166.67%이기 때문에 반드시 게이지가 채워진다. 발동 확률은 해당 동전의 가치에 1/6을 한 값의 백분율이며, 10원짜리 동전인 다임은 10/6 = 1.666... = 166.67%이기 때문에 반드시 게이지가 채워진다.",
    "game_id": "147"
  },
  {
    "id": 832,
    "type": "trinket",
    "name": "우정 목걸이",
    "english_name": "Friendship Necklace",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/H4988siLVaOkJq0XE9tapAPV-xPJVUAhOIeLl8YLc5StPiLzE3kym59SmhoYAYAriOk4jtYbN-ELGps-o4XWEw.png",
    "description": "여기여기 붙어라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터를 따라오는 모든 패밀리어가 캐릭터를 중심으로 돈다.황금 Friendship Necklace나, Mom's Box를 소지 시 회전 속도가빨라진다/훨씬 빨라진다. 황금 Friendship Necklace나, Mom's Box를 소지 시 회전 속도가빨라진다/훨씬 빨라진다.",
    "game_id": "148"
  },
  {
    "id": 833,
    "type": "trinket",
    "name": "패닉 버튼",
    "english_name": "Panic Button",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/UeIE44uAixdY9fZZ16hGMyCTrDPCSbA7d1whGkrdOFCj8Wk_aYRgFLMZ80QMVZxvNYYAHPHEp9POQArYZ_cxPg.png",
    "description": "비상시에 눌러 주세요",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격이 되기 직전에 액티브 아이템을 사용할 수 있다면 해당 액티브 아이템을 즉시 사용한다.황금 Panic Button이나, Mom's Box를 소지 시10%/20%의 확률로 아이템 게이지가 보존된다. 황금 Panic Button이나, Mom's Box를 소지 시10%/20%의 확률로 아이템 게이지가 보존된다.",
    "game_id": "149"
  },
  {
    "id": 834,
    "type": "trinket",
    "name": "파란 열쇠",
    "english_name": "Blue Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/5VnUV9NzW21Qp9ktFI5S1wD_oHF_-DXmjiJL9mVuIg_PyeqlpEU0NqZW-S6rsR_gbe5SV3u5HyOevNz_JKk5_A.webp",
    "description": "방을 살필 수 있어",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "열쇠나 동전이 필요한 문을 그 아이템을 소모하는 대신 두 칸 크기의 특수 방을 클리어함으로써 열 수 있다.해당 특수 방은 Hush 등장 스테이지인 ???의 모습을 하고 있으며, Hush 소환몹들이 몬스터로 등장한다.황금 Blue Key나, Mom's Box 소지 시 방 클리어 보상을2배/3배로 제공한다.특수 방을 클리어한 후에는 원래 가고자 했던 방으로 갈 수 있으며, 그 방으로는 더 이상 돌아갈 수 없다. 해당 특수 방은 Hush 등장 스테이...",
    "game_id": "150"
  },
  {
    "id": 835,
    "type": "trinket",
    "name": "쇠줄",
    "english_name": "Flat File",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/sQSeWX0Z7pRVWpdyaNjPbloFZRdvK214OKoCtT7J3L3LSp9qNtyfQcB0KdNpUd6CpOCQ0BZovXr2Xogik5CQ9A.png",
    "description": "이제 가시는 없어",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "장착 이후 게임 내에서 모든 가시들이 사라진다.황금 Flat File이나, Mom's Box 소지 시추가로 보스들의 가시 공격, Grudge, 가시 철퇴의 가시도 사라진다.A Pound of Flesh의 효과로 생기는 상점의 원형 가시, 그리드 모드 버튼의 가시에는 영향이 없다. 황금 Flat File이나, Mom's Box 소지 시추가로 보스들의 가시 공격, Grudge, 가시 철퇴의 가시도 사라진다.",
    "game_id": "151"
  },
  {
    "id": 836,
    "type": "trinket",
    "name": "망원경 렌즈",
    "english_name": "Telescope Lens",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/aVADw4M0bJGYsLYvIHOsTuaqzdgQrs4PfqvXpyfX4hoKXXfZbU4XIDORsbJ4_aoisC0TW2WYAM8wKPS-WYofjQ.webp",
    "description": "별들을 봐",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "천체관의 기본 등장 확률이 9% /18%/27%증가한다. 첫 천체관이 등장할 확률이 15% 증가한다. 상단의 효과가 중첩된다.",
    "game_id": "152"
  },
  {
    "id": 837,
    "type": "trinket",
    "name": "엄마의 머리뭉치",
    "english_name": "Mom's Lock",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/dop8sUQLy7zCuZbWV65Gey8E7itm74TwYj6QSld_EnCHVSi-GtcKVVK8HdA7fo8bQ6VcqW2EThujJgYCARGy8A.png",
    "description": "잘라낸 엄마의 사랑",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장할 때마다 25% /50%/100%확률로 Mom's (Coin) Purse를 제외한 무작위 Mom's 패시브 아이템의 효과가 발동될 수 있다.",
    "game_id": "153"
  },
  {
    "id": 838,
    "type": "trinket",
    "name": "주사위 가방",
    "english_name": "Dice Bag",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9QCyJacyI2poYlvUbnRLXbnXRjcYUVj4Pl12SDFKQK9-0xMAdREtRXqYoTSKnUaPBtORIH6chGHGec_oARlR0Q.png",
    "description": "한번 더 굴려",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장할 때마다 50% /100%확률로 해당 방에서만 사용할 수 있는 무작위 일회용 주사위가 알약/카드 칸에 생긴다.이미 알약/카드를 소지하고 있었을 경우 Ctrl 키로 교체가 가능하다.D Infinity는 당연히 생기지 않으며 Spindown Dice, Dice Shard도 생기지 않는다. 이미 알약/카드를 소지하고 있었을 경우 Ctrl 키로 교체가 가능하다.",
    "game_id": "154"
  },
  {
    "id": 839,
    "type": "trinket",
    "name": "성스러운 왕관",
    "english_name": "Holy Crown",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/GVjUxYlPN4mmQUt5xRbYfLY2EomVZkkF7iZLoLuPxheZr78CyOzw9OEhKZ4hfSkKX42KMqko262ZapHf3b4baQ.png",
    "description": "성인의 길을 걸어라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Cathedral을 이 장신구를 소지한 채 시작하면 스테이지에 보물방과 상점이 생긴다.생성되는 상점은 일반적인 상점이지만, 보물방은 23가지의 전용 구조 중에서 생성된다.황금 Holy Crown이나, Mom's Box 소지 시More Options가 적용된 보물방과 높은 등급의 상점이 보장되며, 둘 다 소지시지도에 보물방과 상점의 위치가 표시된다. 생성되는 상점은 일반적인 상점이지만, 보물방은 23가지의 전용 구조 중에서 생성된다.",
    "game_id": "155"
  },
  {
    "id": 840,
    "type": "trinket",
    "name": "엄마의 입맞춤",
    "english_name": "Mother's Kiss",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/rbaCFXvL735mw-L1kwZza25YjddcpDfMwdE7FSO1Uq5KJfQSw5l0cZl24aUEnrcneGSyuOdwXd7WgatTuMoPMw.png",
    "description": "체력 증가",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "최대 체력+ 1개/+ 2개/+ 3개(더럽혀진) 키퍼의 코인 하트 체력 또한 증가한다. (더럽혀진) 키퍼의 코인 하트 체력 또한 증가한다.",
    "game_id": "156"
  },
  {
    "id": 841,
    "type": "trinket",
    "name": "찢어진 카드",
    "english_name": "Torn Card",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/QO_qEpjkojDNa8sZcQSSaixc5Q7RIOEoGlPeGFOvjdKP7TIHS9CYEolmcHNAhBt67iThYX43Uhy93cEAjw9x8w.png",
    "description": "죽음이 기다린다",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "15번째 /10번째/5번째눈물이 발사될 때Ipecac + My Reflection 효과가 적용된 눈물이 발사된다.",
    "game_id": "157"
  },
  {
    "id": 842,
    "type": "trinket",
    "name": "찢어진 주머니",
    "english_name": "Torn Pocket",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/fLYYZkjW-5iuJq4vjPQjfBs3dW_R5PcmPZJ3WS5uVNHAOpI6od7YoXTiTtUMwftbWnPxXow-BAuXg-s5VZJx-g.png",
    "description": "구멍난 주머니",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 자신의 동전, 폭탄, 열쇠 중 두 개 /세 개/네 개를 떨어뜨린다.같은 아이템을 두 개 떨어뜨릴 수도 있으며 니켈과 같은 비슷한 종류의 다른 픽업 아이템으로 대신해서 떨어질 수도 있다.소지 개수가 0개인 아이템, 알트 \"???\"의 똥은 발동되지 않는다. 같은 아이템을 두 개 떨어뜨릴 수도 있으며 니켈과 같은 비슷한 종류의 다른 픽업 아이템으로 대신해서 떨어질 수도 있다.",
    "game_id": "158"
  },
  {
    "id": 843,
    "type": "trinket",
    "name": "도금 열쇠",
    "english_name": "Gilded Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ShLkJM9-xJ1gdt8YhyLJkq7H6hsu1q1grAG4etVzzbGkbgI2T68pyRMgyGwWZNtlZbsqZNG2GcYvVQJObCVUww.png",
    "description": "잃는 게 얻는 것",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "최초 습득시에 한해 열쇠 1개를 획득한다. Old Chest와 Mega Chest를 제외한, 앞으로 등장하는 모든 상자가 황금 상자로 등장한다.Dark Room의 시작 방에 등장하는 빨간 상자 4개도 황금 상자로 대체되며, 이 경우 다른 Dark Room의 황금 상자들과 마찬가지로 평범하게 아이템을 드랍한다.",
    "game_id": "159"
  },
  {
    "id": 844,
    "type": "trinket",
    "name": "복주머니",
    "english_name": "Lucky Sack",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/4jY9myFFi3dNDCWg1YBn85hsIZdpKLT9nykvdGUTnQVIkfreqkZGTYRW2GTPvNTZywBDLu3K0fm2QBpBnqpoGQ.png",
    "description": "공짜 물건이다!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "스테이지를 시작할 때마다 자루가 1개 /2개/3개생성된다.",
    "game_id": "160"
  },
  {
    "id": 845,
    "type": "trinket",
    "name": "사악한 왕관",
    "english_name": "Wicked Crown",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/qX813C-LdDqHEzG3P9tVNp_wBBXwDWC3MYUrDNOvZxY3aggzqu_GUdiJ6tfy9VVJQsNfR43sxH8IW6vddbLJCw.png",
    "description": "악인의 길을 걸어라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Sheol을 이 장신구를 소지한 채 시작하면 스테이지에 보물방과 상점이 생긴다.생성되는 상점은 일반적인 상점이지만, 보물방은 22가지의 전용 구조 중에서 생성된다.황금 Wicked Crown이나, Mom's Box 소지 시More Options가 적용된 보물방과 높은 등급의 상점이 보장되며, 둘 다 소지시지도에 보물방과 상점의 위치가 표시된다. 생성되는 상점은 일반적인 상점이지만, 보물방은 22가지의 전용 구조 중에서 생성된다.",
    "game_id": "161"
  },
  {
    "id": 846,
    "type": "trinket",
    "name": "아자젤의 뿔대",
    "english_name": "Azazel's Stump",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/-cRkao0YYujsF7TtwDbl8UBG76L1WkwtZhSAIipfxYFXLUBpxP5bQ92KXLJSRCrVBRfPk9ns0bU6gIMJf6q5-A.webp",
    "description": "내면의 악마를 해방시켜라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방을 클리어할 때마다 33% /50%/100%확률로 캐릭터가 아자젤의 외형으로 변하여 비행 + 짧은 혈사포 공격을 하게 된다. 변신 상태는 몬스터가 있는 방을 클리어하고 그 방을 나갈 때까지 지속된다.만약 황금 Azazel's Stump + Mom's Box 조합이라면 사실상 아자젤을 플레이하는 것과 같게 된다. 만약 황금 Azazel's Stump + Mom's Box 조합이라면 사실상 아자젤을 플레이하는 것과 같게 된다.",
    "game_id": "162"
  },
  {
    "id": 847,
    "type": "trinket",
    "name": "딱총 화약",
    "english_name": "Ring Cap",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/xuaVLReOy8gEi6YR7WmFwuHnH90HN04AtT_AJez6kyGauVyCcasjKxn3M-Eyg8QVc7qbIE7fFlb5MvnzK5l9ZQ.png",
    "description": "폭발을 두배로!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "폭탄을 설치 시 설치한 폭탄 옆에 추가로 폭탄 한 개 /두 개/세 개가 더 설치된 후 동시에 터진다.폭탄에 추가 효과를 부여하는 아이템들의 영향을 받는다. 폭탄에 추가 효과를 부여하는 아이템들의 영향을 받는다.",
    "game_id": "164"
  },
  {
    "id": 848,
    "type": "trinket",
    "name": "지점토",
    "english_name": "Modeling Clay",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/Yi-u-sBgEbxlIVJoEy9K2WUctHzWRW8Ved8WXCt5sOhfx48pUA6bfz2ALlCM_aPtorymuw1Kef-vO-SegPUX3g.png",
    "description": "???",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장할 때마다 50% /100%확률로 입장한 방에 맞는 배열을 가진, summonable 태그가 붙어있는 무작위 패시브 아이템의 효과가 적용된다.무작위 패시브 효과가 적용되었을 경우, 장신구의 모습이 갈색 빛깔을 한 해당 패시브 아이템의 이미지로 바뀐다.배열이 없는 방의 경우 보물방 배열 내에서 정해진다. 무작위 패시브 효과가 적용되었을 경우, 장신구의 모습이 갈색 빛깔을 한 해당 패시브 아이템의 이미지로 바뀐다.",
    "game_id": "166"
  },
  {
    "id": 849,
    "type": "trinket",
    "name": "연마한 뼈",
    "english_name": "Polished Bone",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/J93FRd-sW0Ojvo6nD-0CDsMUf70Lbe7QmwhpWHGBYT1sUNiINHTTDrxTg9yhFBAbfBmw_jUdAIxUsssekpdqNA.png",
    "description": "저 너머의 친구",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방을 클리어할 때마다 25% /33%/50%확률로 영구적으로매혹상태이상에 걸려 있는 (Black) Bony가 소환된다.",
    "game_id": "167"
  },
  {
    "id": 850,
    "type": "trinket",
    "name": "공허한 심장",
    "english_name": "Hollow Heart",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/5xm-7aoNRWnv4SOdU2CSm8c2xVRcO899Bui8yL6zQbGnYJ3vnYrbDHY791sWCHgYrSKRMGBGmMd-yefh7V8WMA.png",
    "description": "위태로운 축복",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "다음 층으로 내려갈 때마다 빈 뼈 하트 체력이 한 칸 /두 칸/세 칸추가된다.하트가 12개 있을 때 가장 오른쪽에 있는 하트가 소울/블랙 하트라면 그 하트를 빈 뼈 하트가 대신한다. 하트가 12개 있을 때 가장 오른쪽에 있는 하트가 소울/블랙 하트라면 그 하트를 빈 뼈 하트가 대신한다.",
    "game_id": "168"
  },
  {
    "id": 851,
    "type": "trinket",
    "name": "아이의 그림",
    "english_name": "Kid's Drawing",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/DZ6KLze_MBbSUI9E1di5Pv3apQlTteG1AFh6o8lRyWbmWKCUvePOPrcWNcK_H54lPMs3C12h4dROPfm-Lf039g.png",
    "description": "낯이 익어 보이는데...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 시 Guppy 아이템 하나 /둘로 취급한다. 다른 Guppy 아이템한 개/ 두 개를 먹으면 Guppy 변신을 완성했다고 처리되며,한 개/ 두 개만 먹고 장착을 해제하면 Guppy 변신이 해제된다.",
    "game_id": "169"
  },
  {
    "id": 852,
    "type": "trinket",
    "name": "수정 열쇠",
    "english_name": "Crystal Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/k9Fvm6J-yhOs78oUXaoCeDxHL4Ns_Ym1AzSX5GAHVrn29ahYFDes8jquojnXILpMWLyJexb0n6vda-Mc6OiqWQ.png",
    "description": "저 너머로의 부름",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방을 클리어할 때마다 33.3% /50%/100%의 확률로 해당 방에서 빨간 방을 생성할 수 있는 곳에 빨간 방 1개가 생성된다.만약 황금 Crystal Key + Mom's Box 조합이 갖춰진다면,일반 방을 클리어할 때마다 빨간 방 1개가 생성된다.빨간 방 내부에서도 장신구가 발동될 수 있으나 일반 방보다는 확률이 낮다. 이 때 13x13 크기를 넘어 에러 방으로 갈 수도 있다.여러 개의 Crystal Key를 소지하거나 흡수했다면 발동 확...",
    "game_id": "170"
  },
  {
    "id": 853,
    "type": "trinket",
    "name": "키퍼의 할인",
    "english_name": "Keeper's Bargain",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/qVscUNxR-oG396pcadY0OHxwrkB4k2v7wW6BbJw_lm7yvhkKIFq47F-EERtl8QBFs0FRFrgrI4x6sg3kq-MPpQ.png",
    "description": "돈은 만국 공통어지",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "체력 거래를 요구하는 아이템들을 50% /100%체력 대신 동전으로 구매할 수 있다.체력 1칸을 요구하는 아이템은 15원, 체력 2칸을 요구하는 아이템은 30원을 요구하며, 황금 Keeper's Bargain + Mom's Box 조합이 갖춰졌다면물품을 할인할 확률이 생긴다.악마방의 경우 동전을 요구해도 악마 거래임은 변함이 없기 때문에 구매 시 천사방이 더 이상 나오지 않는다. 체력 1칸을 요구하는 아이템은 15원, 체력 2칸을 요구하는 아이...",
    "game_id": "171"
  },
  {
    "id": 854,
    "type": "trinket",
    "name": "저주받은 동전",
    "english_name": "Cursed Penny",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9fjdgfKD6qcRRk6PftQ-U1yyWmjZIRYsHnLxEErJpip2LwQJiAPevA_XkqbayamtXv1moMHw2XZmNwRfHuWnaw.png",
    "description": "고통의 화폐",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "동전을 획득 시 다른 방으로 텔레포트한다. 기본적으로는 무작위이나, 동전의 종류에 따라 확률적으로 무작위 방이 아닌 방으로 이동할 수도 있다.페니(1코인): 50% 확률로 아직 클리어하지 않은 일반 방으로 이동한다.1+1 페니(2코인): 50% 확률로 주사위방, 금고, 침대 방으로 이동한다.니켈(5코인): 50% 확률로 보물방, 상점, 책방, 오락실, 도전 방으로 이동한다.다임(10코인): 25% 확률로 악마 방 & 천사 방으로 이동한다.럭키 ...",
    "game_id": "172"
  },
  {
    "id": 855,
    "type": "trinket",
    "name": "네 영혼",
    "english_name": "Your Soul",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/nz0pIp3SZunlKxJl9mkVC3i0wf-5ReSotdSCjIrOW7kIBu-rbom9cUuthUpmAukJdvL1h_BOSm0bNhg2qCcFMQ.png",
    "description": "내게 다오",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "최대 체력을 대가로 거래 시 최대 체력 대신 이 장신구를 소모하여 거래를 할 수 있다.황금 Your Soul이나, Mom's Box 소지 시10%/20%확률로 장신구가 소모되지 않는다.당연히 악마 거래를 이 장신구로 해도 천사방이 더 이상 나오지 않는다. 황금 Your Soul이나, Mom's Box 소지 시10%/20%확률로 장신구가 소모되지 않는다.",
    "game_id": "173"
  },
  {
    "id": 856,
    "type": "trinket",
    "name": "숫자 자석",
    "english_name": "Number Magnet",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/K0CyObcsBpYcBBYfWEywCul-7PJ238bTozfSbADdk2auOUihZh7gR29GRSR1dISEdbKmjK0WWJmoG_fNNd5Nqw.png",
    "description": "6",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "악마방/천사방의 출현 확률을 10% /15%/20%증가시킨다. 소지하는 동안 악마 방에서 Krampus의 출현을 막으며, 악마 방의 구조를 11개의 전용 구조(그리드 모드는 6개)로 고정시킨다.Number Magnet으로 고정되는 악마 방의 구조에서는 악마 방 아이템 0~3개(대부분은 2~3개), 1~3개의 블랙 하트, Sheol에서 출현하는 몬스터 1마리 이상이 나온다.",
    "game_id": "174"
  },
  {
    "id": 857,
    "type": "trinket",
    "name": "이상한 열쇠",
    "english_name": "Strange Key",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/XzHSWxyw53cKeI9f9aj-C4jwpKxuY_gFDbXBM-VYd7MHfPagt-A72-Ri3W0gYWC51e9ecFbO9UdojOIcDbellw.png",
    "description": "이걸로 뭘 열수 있을까?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "It Lives! 격파 후 시간에 관계없이 Hush로 가는 문이 열린다.",
    "game_id": "175"
  },
  {
    "id": 858,
    "type": "trinket",
    "name": "작은 혈전",
    "english_name": "Lil Clot[63]",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/j31DzimzFgzvwjHrd3NdZ6XMKIAv56OAqheNf4-LnTdWParg9Rbuz9YOWDhyLyDvFvvoVcnof7otnc3SalYG8Q.png",
    "description": "꼬마 친구",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "Sumptorium, 더럽혀진 이브의 고유 능력으로 빨간 하트를 소모했을 때 생성되는 빨간 핏덩이 패밀리어 1마리 /2마리/3마리가 생성된다.핏덩이는 아이작을 따라오면서(Ctrl 키로 아이작만 움직이게 할 수 있다) 캐릭터가 눈물을 쏘는 방향을 향해 눈물을 쏘며, 아이작의 공격 형태를 따라온다.핏덩이의 사거리, 연사 속도, 눈물 속도는 캐릭터와 동일하며, 공격력은 캐릭터의 0.35배이다.핏덩이는 적의 공격을 3번 버틸 수 있으며, 죽었을 경우에...",
    "game_id": "176"
  },
  {
    "id": 859,
    "type": "trinket",
    "name": "스티커 문신",
    "english_name": "Temporary Tattoo",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9iDyIkbIP9D_DcCOv7ZwVyGsMn9kIeeWRk_US3CWoYiWs0YRAp-e91RdttyJ-I7YMutNprCsmCOwz4r_-wQVnw.png",
    "description": "더 용감해진 느낌",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "도전 방 클리어 후 상자가 하나 스폰된다. 보스 도전 방 클리어 후 보스 방 배열 패시브 아이템이 하나 생성된다.더럽혀진 키퍼는 해당 패시브 아이템을 공짜로 챙길 수 있다.",
    "game_id": "177"
  },
  {
    "id": 860,
    "type": "trinket",
    "name": "삼킨 M80",
    "english_name": "Swallowed M80[64]",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/s3OzaxEBr_78su0-2fRAOWuFiOL0_Vv0ovUW-2uFr8SWR_O5N7ijowPklJdPUrQbRlkGLOXn0XctR6CnNaGopg.png",
    "description": "쾅!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "피격 시 50% /100%확률로 캐릭터 주변에 폭발이 일어난다.폭발은 Kamikaze!의 폭발과 동일한 판정으로 대미지는 185이며 폭탄 관련 패시브 아이템의 효과를 받는다.악마 거지 및 악마 야바위꾼은 이 폭발에 휘말려 즉시 죽지만 헌혈 기계와 고해실은 터지지 않고 오히려 헌혈 기계/고해실을 터뜨렸을 때 드랍하는 픽업 아이템을 드랍한다. 폭발은 Kamikaze!의 폭발과 동일한 판정으로 대미지는 185이며 폭탄 관련 패시브 아이템의 효과를 받...",
    "game_id": "178"
  },
  {
    "id": 861,
    "type": "trinket",
    "name": "RC 리모콘",
    "english_name": "RC Remote",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/iuo4TQ788A-GOfYzSPgnABNG64rFMiGM_0R9Vgl_dNzLGjJW4TYzpNGUh8vRYdB--3evEcoI_TvEY_KbHp5BHg.png",
    "description": "조종할 수 있는 친구들!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "캐릭터의 뒤를 따라오는 패밀리어들이 캐릭터의 이동 경로를 정확히 따라온다.Ctrl 키를 누르면 캐릭터만 움직이고 패밀리어들은 고정된다. 이해가 되지 않는다면 Jacob and Esau 캐릭터를 생각하면 된다. Ctrl 키를 누르면 캐릭터만 움직이고 패밀리어들은 고정된다. 이해가 되지 않는다면 Jacob and Esau 캐릭터를 생각하면 된다.",
    "game_id": "179"
  },
  {
    "id": 862,
    "type": "trinket",
    "name": "되찾은 영혼",
    "english_name": "Found Soul",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/x6_2dcXraZpJB9uL_pF3LqXjYZpDofvvGmfO_jOsDW2Dyg7e4q8dBXcowvyi6Vjs-EPMehFYEeOy210Cnk5amA.png",
    "description": "마침내!",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "소지 시 유령 패밀리어가 아이작을 따라온다.유령은 아이작을 따라오면서(Ctrl 키로 캐릭터만 움직이게 할 수 있다) 캐릭터가 눈물을 쏘는 방향을 향해 지형 관통 눈물을 쏘며, 아이작의 공격 형태와 일부 아이템의 효과를 따라하고 일부 장신구의 효과를 같이 볼 수 있다.유령의 사거리, 연사 속도, 눈물 속도는 캐릭터와 동일하며, 공격력은 캐릭터의 0.5배 /0.75배/공격력을 그대로 따라간다.캐릭터가 폭탄을 설치할 경우 유령도 같이 폭탄을 설치하며...",
    "game_id": "180"
  },
  {
    "id": 863,
    "type": "trinket",
    "name": "확장팩",
    "english_name": "Expansion Pack",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/jG7UQXJCqScTRpuXzD71F-X_CIHFvklkOESx9KFQFwnex8YWZ866mlizR_4k-jjVJh8Jc_mrifojCDEnbZVMtg.png",
    "description": "더해지는 재미",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "액티브 아이템 사용 시 쿨타임이 1~2칸 /1~3칸인 다른 무작위 액티브 아이템 1개 /2개의 효과가 같이 발동된다.Shoop Da Whoop!와 같이 추가 조작이 필요한 액티브 아이템은 추가 조작으로 아이템을 실질적으로 사용해야 장신구의 효과가 발동되며, 만약 Expansion Pack으로 추가 조작이 필요한 액티브 아이템이 걸렸다면 장신구의 효과가 한 번 더 발동된다.쿨타임이 2칸인 아이템에는 Dead Sea Scrolls이 있기 때문에 쿨...",
    "game_id": "181"
  },
  {
    "id": 864,
    "type": "trinket",
    "name": "베다니의 정수",
    "english_name": "Beth's Essence",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/ynNlDcESyHZl1OGNqoDZWKjrcgQuN2WgEBDaS0crbZnXl_gSAalCdioDPuXNbAt5oXvMCgVnOvgMa5y51IEx8Q.png",
    "description": "미덕의 보상",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "천사 방에 진입할 때 위습 5개가 생성되며 0% /50%/100%확률로 특수한 위습이 생성될 수 있다. 거지에게 기부를 하면 25% 확률로 무작위 위습 1개가 생성된다.",
    "game_id": "182"
  },
  {
    "id": 865,
    "type": "trinket",
    "name": "쌍둥이",
    "english_name": "The Twins",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9__0wgXbjtoZ0rulU7qjgMEqFnuc-hCAc8HIMNdrrW_V6y9NpA_QZp9SY57UjfgC4U1ZiNEdxM8wto93ArtwMA.png",
    "description": "모든 게 두 개로 보이는데...",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장할 때마다 50% 확률로 자신의 패밀리어 중 하나 /하나 ~ 둘/하나 ~ 셋이 복사된다. 패밀리어가 없을 경우 Brother Bobby나 Sister Maggy 중 하나가 대신 생성된다.",
    "game_id": "183"
  },
  {
    "id": 866,
    "type": "trinket",
    "name": "입양 서류",
    "english_name": "Adoption Papers",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/qc59W7FX-UjIp_P6XFQSOFFxShvfMK8QYC9zDQekQV8JLUMwW1Z-lbFYzmgUX3ZiRDxh5yVkdF7kWwfa6rQY5Q.png",
    "description": "가족을 찾아 줘",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "상점에서 상점 배열의 아이템 대신 '아기 상점' 배열 내에 있는 패밀리어를 10원 /5원에,Soul of Lilith를확정적으로 판다.장신구를 드랍하면 가격은 15원 /7원으로 바뀌지만, 팔고 있는 아이템은 바뀌지 않는다. 장신구를 드랍하면 가격은 15원 /7원으로 바뀌지만, 팔고 있는 아이템은 바뀌지 않는다.",
    "game_id": "184"
  },
  {
    "id": 867,
    "type": "trinket",
    "name": "귀뚜라미 다리",
    "english_name": "Cricket Leg",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/m_9NIbIDBSGxfRoBD2FDMHZVo-wZfCc4py0yfNz9yYVgdibMs3env2rORCY17d1Xwu8tE8mjS3H-4iPCpkSxMA.png",
    "description": "우글거림",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적을 처치할 때 그 위치에서 16.67% /33.33%/50%확률로 Locust of xxx 장신구로 생성되는 자폭 파리들 중 한 마리가 스폰된다.",
    "game_id": "185"
  },
  {
    "id": 868,
    "type": "trinket",
    "name": "아폴리온의 절친",
    "english_name": "Apollyon's Best Friend",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/iETX2jJcziXrxVv-w4nFLQIccflm57o3OMs6CEs1rbaF3tsR741vAKZ5-uryk9iSSS3y_5ossdz0hwUChmU8KA.png",
    "description": "공격적인 친구야",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "아군 빨간 파리가 1마리 /2마리/3마리스폰된다.",
    "game_id": "186"
  },
  {
    "id": 869,
    "type": "trinket",
    "name": "깨진 안경",
    "english_name": "Broken Glasses",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/T1T0OHA3CpOpooCXAnopUZJYrFoq18gJVaZvx_36KcdsxLcyuA1m7doHVMscO9_BFnMiomEvHryY1nLh6Y3X6w.png",
    "description": "다 두 개로 보이나?",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "보물방에서 50% /100%의 확률로 무슨 아이템인지 볼 수 없는 아이템이 추가로 하나 등장한다. 하나를 집으면 다른 하나는 사라진다. 대체 루트의 보물방에서 50% /100%확률로 원래 보이지 않는 보물 방 아이템이 무슨 아이템인지 보여준다.",
    "game_id": "187"
  },
  {
    "id": 870,
    "type": "trinket",
    "name": "육각얼음",
    "english_name": "Ice Cube",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/0I5hHTPXNjZfeVEY5jXJm7PdY9QmL8HC0uKDQX5h_yv3dF_iXn1Sv0xCIlKTIFFohikeLBX0n-gaR9VrTB0TuQ.png",
    "description": "얼어붙어라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "방에 입장 시 일부 적들이석화상태이상에 걸린 채로 나타나는데, 이 석화 상태의 적을 석화 지속시간 4초 + 추가 시간 2초 이내에 처치하면 적이빙결된다.빙결에 대한 자세한 설명은Uranus 아이템 항목으로. 빙결에 대한 자세한 설명은Uranus 아이템 항목으로.",
    "game_id": "188"
  },
  {
    "id": 871,
    "type": "trinket",
    "name": "바포메트의 인장",
    "english_name": "Sigil of Baphomet",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/l8BUQUHvFWmC44sfAIcyZzWymSjXfZV34tOiXmz66Npf1wxHvY0cNX5L9KsvE_Ap-to4mFHT6_fVwglDymnttQ.png",
    "description": "죽음을 즐겨라",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "적을 처치할 때마다 1초 /1.5초/2초간 보호막이 생긴다.적을 처치할 경우 지속 시간이 추가로 1초 /1.5초/2초늘어나 최대 5초 /7.5초/10초까지 증가한다. 적을 처치할 경우 지속 시간이 추가로 1초 /1.5초/2초늘어나 최대 5초 /7.5초/10초까지 증가한다.",
    "game_id": "189"
  },
  {
    "id": 872,
    "type": "trinket",
    "name": "즉석 사진",
    "english_name": "The Polaroid",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/5YMAX6plcEdCisB9CMMLcDQWXhuinbgiRAjZZt4UHjRx_OYDpkJ5jMnLeA_khZbMCQQhr2yKZFfpyYY-fIXRIQ.webp",
    "description": "-",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "빨간 하트 체력이 없거나 남은 빨간 하트 체력이 반 칸일 때 피격 시 5초간 보호막이 발동된다.??? 캐릭터 플레이 혹은 소울 하트를 이용한 계약 시 악마 방에서 방어막을 발동시키고 계약하면소울 하트의 소모 없이 아이템을 얻을 수 있다. ??? 캐릭터 플레이 혹은 소울 하트를 이용한 계약 시 악마 방에서 방어막을 발동시키고 계약하면소울 하트의 소모 없이 아이템을 얻을 수 있다.",
    "game_id": "-"
  },
  {
    "id": 873,
    "type": "trinket",
    "name": "게임스퀴드",
    "english_name": "Game Squid",
    "icon": "💎",
    "image_url": "https://i.namu.wiki/i/9uC5pj1TkHH97j7-N3aUnKiM8ZRz9x9zOAfdJsNKxl67XTpRONjmnJUwG5d-CQ8FQ7R4UEfI-BlIN-ApYGu6hg.webp",
    "description": "-",
    "cooldown": "",
    "unlock_condition": "",
    "location": "",
    "grade": "",
    "effect": "공격 시 일정 확률로 맞은 적에게둔화상태이상을 거는 눈물을 발사한다. 리버스 발매 이후 업데이트된 오리지널의 이터널 에디션 패치에서 등장한 장신구이기 때문에 당연히 리버스에는 존재하지 않으나, 이후 마지막 DLC인 리펜턴스에서 동일한 효과를 가진 장신구인 Chewed Pen이 추가되었다.",
    "game_id": "-"
  }
];